import { Personaje } from '../engine/personaje.js';

// ============================================================================
// BASE DE DATOS MASIVA DE PERSONAJES (MULTIVERSO RPG)
// ============================================================================

export const rawNpcsDB = {
    // ORIGINALES
    kaito: { id: "kaito", name: "Kaito", desc: "Un muchacho misterioso con ropa informal y una mirada observadora.", room: "salon_central", tags: ["sabio_serio", "misterioso", "observador"], favoritePlace: "mirador_estrellas", universo: "Originales", hp: 110, fuerza: 14, defensa: 8, mana: 80, alineacion: "Neutral", habilidadEspecial: "Ojo Analitico" },
    doomentio: { id: "doomentio", name: "Doomentio", desc: "Un tipo de aspecto demacrado y postura rígida, dando discursos hiperanalíticos.", room: "salon_central", tags: ["serio", "critico", "egocentrico"], favoritePlace: "biblioteca_misteriosa", universo: "Originales", hp: 90, fuerza: 8, defensa: 4, mana: 100, alineacion: "Caotico", habilidadEspecial: "Critica Destructiva" },
    grant: { id: "grant", name: "Grant", desc: "Un sujeto tranquilo de modales pausados, ajustándose los lentes mientras analiza la arquitectura.", room: "salon_central", tags: ["sabio_serio", "analitico", "tranquilo"], favoritePlace: "planetario_cuantico", universo: "Originales", hp: 100, fuerza: 10, defensa: 10, mana: 90, alineacion: "Neutral", habilidadEspecial: "Calculo Estructural" },
    pepsiman: { id: "pepsiman", name: "Pepsiman", desc: "El legendario héroe plateado y azul corriendo en el lugar a toda velocidad.", room: "salon_central", tags: ["alegre", "caotico", "comico", "heroico"], favoritePlace: "pista_patinaje", universo: "Originales", hp: 150, fuerza: 18, defensa: 12, mana: 60, alineacion: "Heroe", habilidadEspecial: "Tacleada Refrescante" },

    // DC (Expandido)
    batman: { id: "batman", name: "Batman (Bruce Wayne)", desc: "El Caballero de la Noche. Envuelto en su capa negra, observa minuciosamente desde las sombras.", room: "universo_dc", tags: ["edgy", "serio", "estratega", "heroico"], favoritePlace: "azotea_gothica", universo: "Universo DC", hp: 180, fuerza: 25, defensa: 20, mana: 70, alineacion: "Heroe", habilidadEspecial: "Batarang Explosivo" },
    superman: { id: "superman", name: "Superman (Clark Kent)", desc: "El Hombre de Acero, flotando a pocos centímetros del suelo con una sonrisa cálida.", room: "universo_dc", tags: ["heroico", "alegre", "lider", "protector"], favoritePlace: "picnic_campo", universo: "Universo DC", hp: 500, fuerza: 95, defensa: 90, mana: 100, alineacion: "Heroe", habilidadEspecial: "Vision Laser" },
    dick_grayson: { id: "dick_grayson", name: "Nightwing (Dick Grayson)", desc: "El primer Robin, vistiendo su traje negro y azul de Nightwing. Mantiene una postura ágil.", room: "universo_dc", tags: ["alegre", "heroico", "carismatico", "lider"], favoritePlace: "club_gay_striptease", universo: "Universo DC", hp: 160, fuerza: 22, defensa: 15, mana: 60, alineacion: "Heroe", habilidadEspecial: "Bastones Escrima" },
    tim_drake: { id: "tim_drake", name: "Red Robin (Tim Drake)", desc: "El detective prodigio de la Batifamilia, tecleando rápidamente en un dispositivo holográfico.", room: "universo_dc", tags: ["sabio_serio", "analitico", "heroico"], favoritePlace: "cafe_gourmet", universo: "Universo DC", hp: 150, fuerza: 19, defensa: 14, mana: 80, alineacion: "Heroe", habilidadEspecial: "Hackeo Táctico" },
    damian_wayne: { id: "damian_wayne", name: "Robin (Damian Wayne)", desc: "El hijo biológico de Bruce Wayne. Cruza los brazos con gesto desafiante.", room: "universo_dc", tags: ["edgy", "orgulloso", "agresivo", "heroico"], favoritePlace: "dojo_artes_marciales", universo: "Universo DC", hp: 140, fuerza: 21, defensa: 12, mana: 50, alineacion: "Antiheroe", habilidadEspecial: "Corte de Katana" },
    thomas_wayne: { id: "thomas_wayne", name: "Batman de Flashpoint (Thomas Wayne)", desc: "Un Batman más viejo, de ojos cansados, traje oscuro con detalles rojos y dos pistolas.", room: "universo_dc", tags: ["edgy", "serio", "rudo", "antiheroe"], favoritePlace: "bar_subterraneo", universo: "Universo DC", hp: 190, fuerza: 28, defensa: 18, mana: 40, alineacion: "Antiheroe", habilidadEspecial: "Disparo Calibre 45" },
    conner_kent: { id: "conner_kent", name: "Superboy (Conner Kent / Kon-El)", desc: "Un joven de actitud rebelde con chamarra de cuero y la icónica 'S' roja.", room: "universo_dc", tags: ["rebelde", "carismatico", "heroico", "orgulloso"], favoritePlace: "concierto_rock", universo: "Universo DC", hp: 320, fuerza: 60, defensa: 50, mana: 70, alineacion: "Heroe", habilidadEspecial: "Telequinesis Tactil" },
    bart_allen: { id: "bart_allen", name: "Kid Flash (Bart Allen)", desc: "Un velocista hiperactivo que no puede quedarse quieto un solo segundo.", room: "universo_dc", tags: ["alegre", "hiperactivo", "comico", "heroico"], favoritePlace: "parque_atracciones", universo: "Universo DC", hp: 140, fuerza: 18, defensa: 12, mana: 90, alineacion: "Heroe", habilidadEspecial: "Tornado de Velocidad" },
    beast_boy: { id: "beast_boy", name: "Chico Bestia (Garfield Logan)", desc: "Un chico de piel verde brillante y sonrisa burlona con su uniforme de los Titanes.", room: "universo_dc", tags: ["alegre", "comico", "amigable", "heroico"], favoritePlace: "puesto_comida_callejera", universo: "Universo DC", hp: 170, fuerza: 24, defensa: 16, mana: 80, alineacion: "Heroe", habilidadEspecial: "Transformación Gorila" },
    blue_beetle: { id: "blue_beetle", name: "Blue Beetle (Jaime Reyes)", desc: "Un muchacho enfundado en una armadura alienígena azul brillante.", room: "universo_dc", tags: ["alegre", "heroico", "amigable", "joven"], favoritePlace: "arcade_retro", universo: "Universo DC", hp: 220, fuerza: 35, defensa: 30, mana: 100, alineacion: "Heroe", habilidadEspecial: "Cañón de Plasma Escarabajo" },
    darkseid: { id: "darkseid", name: "Darkseid", desc: "El tirano de Apokolips. Con las manos a la espalda, impone un aura de opresión pura.", room: "universo_dc", tags: ["imponente", "villano", "dominante", "dios"], favoritePlace: "trono_apokolips", universo: "Universo DC", hp: 600, fuerza: 100, defensa: 95, mana: 120, alineacion: "Villano", habilidadEspecial: "Rayos Omega" },
    bane: { id: "bane", name: "Bane", desc: "Un gigante musculoso con máscara de luchador, con tubos inyectando Veneno en su cuello.", room: "universo_dc", tags: ["fuerza_bruta", "estratega", "villano"], favoritePlace: "gimnasio_subterraneo", universo: "Universo DC", hp: 280, fuerza: 55, defensa: 35, mana: 30, alineacion: "Villano", habilidadEspecial: "Quebradora de Espalda" },
    doomsday: { id: "doomsday", name: "Doomsday", desc: "Una monstruosidad de huesos sobresalientes y furia incontrolable.", room: "universo_dc", tags: ["fuerza_bruta", "monstruo", "destructivo"], favoritePlace: "crater_desolado", universo: "Universo DC", hp: 550, fuerza: 92, defensa: 85, mana: 0, alineacion: "Villano", habilidadEspecial: "Adaptacion Reactiva" },
    lobo: { id: "lobo", name: "Lobo", desc: "El mercenario czarniano fumando un puro gigante con su cadena con gancho al hombro.", room: "universo_dc", tags: ["antiheroe", "caotico", "fuerza_bruta", "mercenario"], favoritePlace: "bar_espacial", universo: "Universo DC", hp: 450, fuerza: 80, defensa: 70, mana: 40, alineacion: "Antiheroe", habilidadEspecial: "Gancho Czarniano" },
    shazam: { id: "shazam", name: "Shazam", desc: "Un héroe musculoso con capa blanca que desprende rayos mágicos del pecho.", room: "universo_dc", tags: ["heroico", "alegre", "magico", "dios"], favoritePlace: "roca_eternidad", universo: "Universo DC", hp: 480, fuerza: 88, defensa: 80, mana: 110, alineacion: "Heroe", habilidadEspecial: "Rayo de Zeus" },
    killer_croc: { id: "killer_croc", name: "Killer Croc", desc: "Un reptil humanoide gigantesco rugiendo con mandíbulas llenas de dientes afilados.", room: "universo_dc", tags: ["monstruo", "fuerza_bruta", "agresivo"], favoritePlace: "alcantarillas_gotham", universo: "Universo DC", hp: 260, fuerza: 48, defensa: 40, mana: 10, alineacion: "Villano", habilidadEspecial: "Mordisco Devorador" },
    black_adam: { id: "black_adam", name: "Black Adam", desc: "El antiguo gobernante de Kahndaq vistiendo su traje negro con rayo dorado en el pecho.", room: "universo_dc", tags: ["antiheroe", "orgulloso", "imponente", "magico"], favoritePlace: "palacio_kahndaq", universo: "Universo DC", hp: 490, fuerza: 90, defensa: 82, mana: 100, alineacion: "Antiheroe", habilidadEspecial: "Ira de Atenea" },
    metallo: { id: "metallo", name: "Metallo", desc: "Un cyborg con esqueleto de titanio cuyo corazón brilla con Kryptonita verde.", room: "universo_dc", tags: ["cyborg", "villano", "tecnologico"], favoritePlace: "fabrica_abandonada", universo: "Universo DC", hp: 300, fuerza: 50, defensa: 60, mana: 50, alineacion: "Villano", habilidadEspecial: "Rayo de Kryptonita" },
    mongul: { id: "mongul", name: "Mongul", desc: "El masivo tirano alienígena de piel amarilla y armadura de combate.", room: "universo_dc", tags: ["imponente", "villano", "conquistador"], favoritePlace: "mundo_guerra", universo: "Universo DC", hp: 420, fuerza: 75, defensa: 65, mana: 40, alineacion: "Villano", habilidadEspecial: "Puño del Conquistador" },
    atrocitus: { id: "atrocitus", name: "Atrocitus", desc: "El líder de los Red Lanterns, escupiendo plasma rojo hirviendo cargado de ira.", room: "universo_dc", tags: ["caotico", "agresivo", "ira", "alienigena"], favoritePlace: "volcan_ryut", universo: "Universo DC", hp: 380, fuerza: 70, defensa: 55, mana: 90, alineacion: "Villano", habilidadEspecial: "Vómito de Plasma de Ira" },
    solomon_grundy: { id: "solomon_grundy", name: "Solomon Grundy", desc: "Un enorme zombi grisáceo balbuceando su antigua rima infantil.", room: "universo_dc", tags: ["zombi", "fuerza_bruta", "lento"], favoritePlace: "pantano_de la_muerte", universo: "Universo DC", hp: 350, fuerza: 60, defensa: 30, mana: 0, alineacion: "Villano", habilidadEspecial: "Aplastamiento Inmortal" },

    // MARVEL
    hulk: { id: "hulk", name: "Hulk", desc: "El gigante verde de masa muscular descontrolada rugiendo con furia cósmica.", room: "universo_marvel", tags: ["fuerza_bruta", "agresivo", "monstruo", "heroico"], favoritePlace: "laboratorio_destruido", universo: "Universo Marvel", hp: 520, fuerza: 98, defensa: 85, mana: 0, alineacion: "Heroe", habilidadEspecial: "Aplastamiento Hulk" },
    thor: { id: "thor", name: "Thor Odinson", desc: "El Dios del Trueno sosteniendo a Mjolnir mientras centellas azules brillan en sus ojos.", room: "universo_marvel", tags: ["dios", "heroico", "magico", "lider"], favoritePlace: "salón_asgard", universo: "Universo Marvel", hp: 480, fuerza: 88, defensa: 78, mana: 100, alineacion: "Heroe", habilidadEspecial: "Invocacion del Trueno" },
    juggernaut: { id: "juggernaut", name: "Juggernaut (Cain Marko)", desc: "Una fuerza imparable envuelta en una celada de metal impenetrable.", room: "universo_marvel", tags: ["fuerza_bruta", "imparable", "villano"], favoritePlace: "zona_impacto", universo: "Universo Marvel", hp: 450, fuerza: 80, defensa: 90, mana: 20, alineacion: "Villano", habilidadEspecial: "Carga Imparable" },
    colossus: { id: "colossus", name: "Colossus (Piotr Rasputin)", desc: "El mutante ruso cuya piel se transforma en acero orgánico brillante.", room: "universo_marvel", tags: ["fuerza_bruta", "tanque", "heroico"], favoritePlace: "mansión_x", universo: "Universo Marvel", hp: 350, fuerza: 65, defensa: 75, mana: 30, alineacion: "Heroe", habilidadEspecial: "Lanzamiento de Viajero" },
    sabretooth: { id: "sabretooth", name: "Sabretooth (Victor Creed)", desc: "Un depredador feroz con colmillos, garras y un factor de curación salvaje.", room: "universo_marvel", tags: ["agresivo", "depredador", "villano"], favoritePlace: "bosque_nevado", universo: "Universo Marvel", hp: 280, fuerza: 45, defensa: 30, mana: 20, alineacion: "Villano", habilidadEspecial: "Desgarro Salvaje" },
    venom: { id: "venom", name: "Venom (Eddie Brock)", desc: "El simbionte alienígena negro mostrando una enorme lengua y colmillos blancos.", room: "universo_marvel", tags: ["simbionte", "antiheroe", "agresivo"], favoritePlace: "callejon_oscuro", universo: "Universo Marvel", hp: 310, fuerza: 58, defensa: 45, mana: 50, alineacion: "Antiheroe", habilidadEspecial: "Devorador Simbiotico" },
    luke_cage: { id: "luke_cage", name: "Luke Cage", desc: "El héroe de Harlem con piel impenetrable y puños como mazos de demolición.", room: "universo_marvel", tags: ["fuerza_bruta", "tanque", "heroico"], favoritePlace: "barrio_harlem", universo: "Universo Marvel", hp: 300, fuerza: 52, defensa: 65, mana: 20, alineacion: "Heroe", habilidadEspecial: "Puñetazo de Titanio" },
    kingpin: { id: "kingpin", name: "Kingpin (Wilson Fisk)", desc: "Un hombre masivo en traje blanco que domina el crimen con intelecto y fuerza pura.", room: "universo_marvel", tags: ["estratega", "mafia", "villano"], favoritePlace: "penthouse_fisk", universo: "Universo Marvel", hp: 200, fuerza: 35, defensa: 25, mana: 40, alineacion: "Villano", habilidadEspecial: "Abrazo de Oso Morder" },
    kraven: { id: "kraven", name: "Kraven el Cazador", desc: "El cazador definitivo vistiendo un chaleco de piel de león y portando lanzas.", room: "universo_marvel", tags: ["cazador", "estratega", "villano"], favoritePlace: "selva_reservada", universo: "Universo Marvel", hp: 220, fuerza: 38, defensa: 28, mana: 30, alineacion: "Villano", habilidadEspecial: "Trampa de Cazador" },
    hercules_marvel: { id: "hercules_marvel", name: "Hercules", desc: "El León de Olimpo. Un semidios sonriente siempre listo para la riña y el vino.", room: "universo_marvel", tags: ["dios", "fuerza_bruta", "heroico"], favoritePlace: "taberna_mitica", universo: "Universo Marvel", hp: 420, fuerza: 82, defensa: 70, mana: 60, alineacion: "Heroe", habilidadEspecial: "Maza de Adamantio" },
    spiderman: { id: "spiderman", name: "Spider-Man (Peter Parker)", desc: "El trepamuros vistiendo su traje rojo y azul, balanceándose con chistes constantes.", room: "universo_marvel", tags: ["heroico", "alegre", "agil", "comico"], favoritePlace: "azotea_manhattan", universo: "Universo Marvel", hp: 210, fuerza: 42, defensa: 30, mana: 80, alineacion: "Heroe", habilidadEspecial: "Impacto de Telaraña" },
    miles_morales: { id: "miles_morales", name: "Miles Morales", desc: "El Spider-Man de Brooklyn con su traje negro y rojo, emanando chispas bioeléctricas.", room: "universo_marvel", tags: ["heroico", "joven", "agil"], favoritePlace: "mural_grafiti", universo: "Universo Marvel", hp: 190, fuerza: 38, defensa: 25, mana: 90, alineacion: "Heroe", habilidadEspecial: "Rayo Venom Bioelectrico" },
    wiccan: { id: "wiccan", name: "Wiccan (William Kaplan)", desc: "Un joven hechicero con capa roja manipulando energía mágica azul en sus manos.", room: "universo_marvel", tags: ["mago", "heroico", "joven"], favoritePlace: "santuario_místico", universo: "Universo Marvel", hp: 160, fuerza: 15, defensa: 20, mana: 150, alineacion: "Heroe", habilidadEspecial: "Distorsión de Realidad" },
    thanos: { id: "thanos", name: "Thanos", desc: "El Titan Loco. Viste armadura dorada y el Guantelete del Infinito resplandece en su mano.", room: "universo_marvel", tags: ["villano", "imponente", "conquistador", "dios"], favoritePlace: "santuario_espacial", universo: "Universo Marvel", hp: 580, fuerza: 96, defensa: 90, mana: 130, alineacion: "Villano", habilidadEspecial: "Chasquido de Gemas" },

    // Dragon Ball
    goku: { id: "goku", name: "Son Goku", desc: "El saiyajin criado en la Tierra con su traje naranja, sonriendo entusiasmado por pelear.", room: "universo_dragon_ball", tags: ["heroico", "alegre", "fuerte", "competitivo"], favoritePlace: "montaña_paoz", universo: "Universo Dragon Ball", hp: 450, fuerza: 85, defensa: 75, mana: 120, alineacion: "Heroe", habilidadEspecial: "Kamehameha" },
    vegeta: { id: "vegeta", name: "Vegeta", desc: "El Príncipe de los Saiyajin. Mantiene los brazos cruzados con una mueca de orgullo indomable.", room: "universo_dragon_ball", tags: ["orgulloso", "competitivo", "serio", "antiheroe"], favoritePlace: "camara_gravedad", universo: "Universo Dragon Ball", hp: 440, fuerza: 84, defensa: 74, mana: 115, alineacion: "Antiheroe", habilidadEspecial: "Final Flash" },
    frieza: { id: "frieza", name: "Frieza (Freezer)", desc: "El emperador del universo en su forma final, flotando con una sonrisa malévola.", room: "universo_dragon_ball", tags: ["villano", "tirano", "orgulloso"], favoritePlace: "nave_espacial_frieza", universo: "Universo Dragon Ball", hp: 420, fuerza: 80, defensa: 70, mana: 110, alineacion: "Villano", habilidadEspecial: "Supernova" },
    piccolo: { id: "piccolo", name: "Piccolo", desc: "El guerrero namekuseijin parado e inmóvil con su pesada capa blanca flotando con el viento.", room: "universo_dragon_ball", tags: ["sabio_serio", "estratega", "solitario", "protector"], favoritePlace: "cascada_entrenamiento", universo: "Universo Dragon Ball", hp: 320, fuerza: 55, defensa: 50, mana: 95, alineacion: "Heroe", habilidadEspecial: "Makankosappo" },
    cell: { id: "cell", name: "Cell (Perfecto)", desc: "El bio-androide perfecto cruzado de brazos, derramando un aura verde de confianza absolute.", room: "universo_dragon_ball", tags: ["villano", "orgulloso", "perfeccion"], favoritePlace: "arena_cell_games", universo: "Universo Dragon Ball", hp: 400, fuerza: 78, defensa: 68, mana: 105, alineacion: "Villano", habilidadEspecial: "Kamehameha Solar" },
    beerus: { id: "beerus", name: "Bills (Beerus)", desc: "El Dios de la Destrucción del Universo 7, rascándose la oreja con aburrimiento.", room: "universo_dragon_ball", tags: ["dios", "caotico", "comelon", "poderoso"], favoritePlace: "templo_destruccion", universo: "Universo Dragon Ball", hp: 600, fuerza: 100, defensa: 95, mana: 150, alineacion: "Neutral", habilidadEspecial: "Hakai" },
    zamasu: { id: "zamasu", name: "Zamasu", desc: "El aprendiz de Kaiō Shin con túnica verde, mirando a los mortales con desprecio sagrado.", room: "universo_dragon_ball", tags: ["villano", "divino", "egocentrico"], favoritePlace: "templo_kaioshin", universo: "Universo Dragon Ball", hp: 350, fuerza: 60, defensa: 65, mana: 110, alineacion: "Villano", habilidadEspecial: "Tajo de Energia Sagrada" },
    goku_black: { id: "goku_black", name: "Goku Black", desc: "Zamasu en el cuerpo de Goku vistiendo túnica gris y un anillo del tiempo.", room: "universo_dragon_ball", tags: ["villano", "edgy", "orgulloso"], favoritePlace: "ciudad_destruida_futuro", universo: "Universo Dragon Ball", hp: 430, fuerza: 82, defensa: 72, mana: 120, alineacion: "Villano", habilidadEspecial: "Kamehameha Oscuro" },
    gohan_adulto: { id: "gohan_adulto", name: "Gohan (Adulto)", desc: "Vestido con su gi morado de combate, transmite una calma sabia y una fuerza oculta.", room: "universo_dragon_ball", tags: ["sabio_serio", "tranquilo", "heroico", "estudioso"], favoritePlace: "biblioteca_misteriosa", universo: "Universo Dragon Ball", hp: 410, fuerza: 82, defensa: 70, mana: 100, alineacion: "Heroe", habilidadEspecial: "Masenko Definitivo" },
    gohan_nino: { id: "gohan_nino", name: "Gohan (Niño)", desc: "El pequeño Gohan vistiendo su traje con el kanji de Kame. Mira con curiosidad.", room: "universo_dragon_ball", tags: ["alegre", "inocente", "timido", "heroico"], favoritePlace: "picnic_campo", universo: "Universo Dragon Ball", hp: 200, fuerza: 30, defensa: 20, mana: 60, alineacion: "Heroe", habilidadEspecial: "Ráfaga de Furia" },
    trunks_nino: { id: "trunks_nino", name: "Trunks (Niño)", desc: "El hijo mestizo de Vegeta, confiado y con las manos en los bolsillos.", room: "universo_dragon_ball", tags: ["alegre", "orgulloso", "travieso", "competitivo"], favoritePlace: "arcade_retro", universo: "Universo Dragon Ball", hp: 210, fuerza: 32, defensa: 22, mana: 60, alineacion: "Heroe", habilidadEspecial: "Cañón Buster" },
    trunks_futuro: { id: "trunks_futuro", name: "Trunks del Futuro", desc: "El guerrero peli-violeta con su chaqueta de Capsule Corp y su espada cruzada.", room: "universo_dragon_ball", tags: ["edgy", "serio", "heroico", "protector"], favoritePlace: "mirador_estrellas", universo: "Universo Dragon Ball", hp: 380, fuerza: 75, defensa: 65, mana: 95, alineacion: "Heroe", habilidadEspecial: "Corte de Espada Luz" },
    android_17: { id: "android_17", name: "Androide 17", desc: "El protector de la fauna silvestre, luciendo su brazalete de Ranger y mirada indiferente.", room: "universo_dragon_ball", tags: ["solitario", "tranquilo", "edgy", "protector"], favoritePlace: "bosque_encantado", universo: "Universo Dragon Ball", hp: 390, fuerza: 76, defensa: 80, mana: 90, alineacion: "Heroe", habilidadEspecial: "Barrera de Androide" },
    kaio_shin: { id: "kaio_shin", name: "Kaiō Shin del Este", desc: "La deidad del Universo 7, observando la convergencia multiversal con preocupación.", room: "universo_dragon_ball", tags: ["sabio_serio", "divino", "precavido"], favoritePlace: "jardin_botanico", universo: "Universo Dragon Ball", hp: 250, fuerza: 40, defensa: 45, mana: 120, alineacion: "Heroe", habilidadEspecial: "Telequinesis Divina" },
    majin_buu_gordo: { id: "majin_buu_gordo", name: "Majin Buu (Gordo)", desc: "El ser rosado y rechoncho saltando felizmente mientras busca chocolates.", room: "universo_dragon_ball", tags: ["alegre", "comelon", "caotico", "inocente"], favoritePlace: "pasteleria_magica", universo: "Universo Dragon Ball", hp: 420, fuerza: 70, defensa: 75, mana: 80, alineacion: "Neutral", habilidadEspecial: "Rayo Convertidor de Chocolate" },
    super_buu: { id: "super_buu", name: "Super Buu", desc: "La versión estilizada y cruel de Buu, tronándose el cuello con mirada asesina.", room: "universo_dragon_ball", tags: ["villano", "caotico", "monstruo"], favoritePlace: "palacio_sagrado", universo: "Universo Dragon Ball", hp: 460, fuerza: 86, defensa: 76, mana: 100, alineacion: "Villano", habilidadEspecial: "Ataque Extincion Humana" },
    kid_buu: { id: "kid_buu", name: "Kid Buu", desc: "La forma original de Buu. Se golpea el pecho como un salvaje y se ríe descontroladamente.", room: "universo_dragon_ball", tags: ["villano", "caotico", "maniaco", "destructivo"], favoritePlace: "planeta_kaioshin", universo: "Universo Dragon Ball", hp: 470, fuerza: 88, defensa: 78, mana: 110, alineacion: "Villano", habilidadEspecial: "Bola Destructora Planetaria" },
    broly_z: { id: "broly_z", name: "Broly (DBZ)", desc: "El Saiyajin Legendario envuelto en un aura verde gigante gritando el nombre de Kakarotto.", room: "universo_dragon_ball", tags: ["fuerza_bruta", "monstruo", "agresivo"], favoritePlace: "planeta_nuevo_vegeta", universo: "Universo Dragon Ball", hp: 510, fuerza: 94, defensa: 85, mana: 80, alineacion: "Villano", habilidadEspecial: "Bomba Borradora" },
    bardock: { id: "bardock", name: "Bardock", desc: "El padre de Goku con la pañoleta roja ensangrentada en la frente y armadura saiyajin.", room: "universo_dragon_ball", tags: ["guerrero", "serio", "orgulloso", "heroico"], favoritePlace: "orbita_planeta_vegeta", universo: "Universo Dragon Ball", hp: 300, fuerza: 58, defensa: 45, mana: 70, alineacion: "Heroe", habilidadEspecial: "Gatillo Espiritual" },
    raditz: { id: "raditz", name: "Raditz", desc: "El hermano mayor de Goku con melena larga hasta la cintura y rastreador en el ojo.", room: "universo_dragon_ball", tags: ["villano", "orgulloso", "agresivo"], favoritePlace: "zona_aterrizaje_capsula", universo: "Universo Dragon Ball", hp: 180, fuerza: 28, defensa: 20, mana: 40, alineacion: "Villano", habilidadEspecial: "Fin del Sábado" },
    nappa: { id: "nappa", name: "Nappa", desc: "El calvo e imponente guerrero saiyajin de elite, tronándose los nudillos.", room: "universo_dragon_ball", tags: ["fuerza_bruta", "villano", "agresivo"], favoritePlace: "ciudad_destruida", universo: "Universo Dragon Ball", hp: 240, fuerza: 40, defensa: 30, mana: 30, alineacion: "Villano", habilidadEspecial: "Volcano Eruption" },
    turles: { id: "turles", name: "Turles", desc: "El pirata espacial identico a Goku comiendo un fruto del Árbol del Poder.", room: "universo_dragon_ball", tags: ["villano", "ambicioso", "cruel"], favoritePlace: "arbol_del_poder", universo: "Universo Dragon Ball", hp: 290, fuerza: 52, defensa: 40, mana: 60, alineacion: "Villano", habilidadEspecial: "Corta Matar" },
    cooler: { id: "cooler", name: "Cooler", desc: "El hermano mayor de Frieza en su quinta forma con máscara blindada.", room: "universo_dragon_ball", tags: ["villano", "orgulloso", "imponente"], favoritePlace: "planeta_super_metami", universo: "Universo Dragon Ball", hp: 410, fuerza: 79, defensa: 72, mana: 90, alineacion: "Villano", habilidadEspecial: "Supernova de Super Cooler" },
    janemba: { id: "janemba", name: "Janemba", desc: "El demonio rojo de espadas dimensionales alterando la realidad del infierno.", room: "universo_dragon_ball", tags: ["caotico", "villano", "mago", "monstruo"], favoritePlace: "infierno_cristalino", universo: "Universo Dragon Ball", hp: 440, fuerza: 83, defensa: 75, mana: 100, alineacion: "Villano", habilidadEspecial: "Espada de Ilusión" },
    gogeta: { id: "gogeta", name: "Gogeta", desc: "La fusión por danza de Goku y Vegeta portando el chaleco Metamor con halo de poder.", room: "universo_dragon_ball", tags: ["fusion", "heroico", "confiado", "fuerte"], favoritePlace: "campo_batalla_volcanico", universo: "Universo Dragon Ball", hp: 550, fuerza: 96, defensa: 90, mana: 130, alineacion: "Heroe", habilidadEspecial: "Castigador de Almas" },
    vegito: { id: "vegito", name: "Vegito", desc: "La fusión por pendientes Pothara, cruzado de brazos lanzando chistes al enemigo.", room: "universo_dragon_ball", tags: ["fusion", "heroico", "orgulloso", "fuerte"], favoritePlace: "planeta_kaioshin", universo: "Universo Dragon Ball", hp: 560, fuerza: 97, defensa: 91, mana: 135, alineacion: "Heroe", habilidadEspecial: "Espada de Espiritu" },
    gotenks: { id: "gotenks", name: "Gotenks", desc: "La fusión de Goten y Trunks presumiendo sus poses dramáticas.", room: "universo_dragon_ball", tags: ["fusion", "alegre", "comico", "orgulloso"], favoritePlace: "habitacion_tiempo", universo: "Universo Dragon Ball", hp: 320, fuerza: 60, defensa: 50, mana: 85, alineacion: "Heroe", habilidadEspecial: "Super Fantasma Kamikaze" },
    zamas_fusion: { id: "zamas_fusion", name: "Zamas Fusión", desc: "La fusión divina con halo de luz blanca a sus espaldas proclamandose dios definitivo.", room: "universo_dragon_ball", tags: ["fusion", "villano", "divino", "dramatico"], favoritePlace: "cielo_desolado", universo: "Universo Dragon Ball", hp: 500, fuerza: 90, defensa: 88, mana: 140, alineacion: "Villano", habilidadEspecial: "Ira Divina" },
    krilin: { id: "krilin", name: "Krilin", desc: "El experto artesano marcial humano con los seis puntos marcados en su frente.", room: "universo_dragon_ball", tags: ["heroico", "amigable", "humilde"], favoritePlace: "kame_house", universo: "Universo Dragon Ball", hp: 180, fuerza: 28, defensa: 20, mana: 50, alineacion: "Heroe", habilidadEspecial: "Kienzan" },
    yamcha: { id: "yamcha", name: "Yamcha", desc: "El ex-bandido del desierto luciendo su cicatriz facial y sonrisa confiada.", room: "universo_dragon_ball", tags: ["heroico", "amigable", "confiado"], favoritePlace: "estadio_beisbol", universo: "Universo Dragon Ball", hp: 160, fuerza: 22, defensa: 18, mana: 40, alineacion: "Heroe", habilidadEspecial: "Golpe del Colmillo de Lobo" },
    tenshinhan: { id: "tenshinhan", name: "Tenshinhan", desc: "El estricto guerrero de tres ojos con su túnica verde y postura austera.", room: "universo_dragon_ball", tags: ["sabio_serio", "disciplinado", "heroico"], favoritePlace: "cascada_entrenamiento", universo: "Universo Dragon Ball", hp: 220, fuerza: 36, defensa: 28, mana: 60, alineacion: "Heroe", habilidadEspecial: "Kikohu" },
    chaoz: { id: "chaoz", name: "Chaoz", desc: "El pequeño muñeco vampírico compañero de Tenshinhan con mejillas rojas.", room: "universo_dragon_ball", tags: ["amigable", "mago", "inocente"], favoritePlace: "cascada_entrenamiento", universo: "Universo Dragon Ball", hp: 120, fuerza: 12, defensa: 10, mana: 80, alineacion: "Heroe", habilidadEspecial: "Paralisis Telequinetica" },
    whis: { id: "whis", name: "Whis", desc: "El Ángel del Universo 7 flotando suavemente con su cetro mágico y sonrisa apacible.", room: "universo_dragon_ball", tags: ["dios", "comelon", "mago", "tranquilo"], favoritePlace: "templo_destruccion", universo: "Universo Dragon Ball", hp: 700, fuerza: 120, defensa: 110, mana: 200, alineacion: "Neutral", habilidadEspecial: "Retroceso Temporal" },
    gran_sacerdote: { id: "gran_sacerdote", name: "Gran Sacerdote (Daishinkan)", desc: "El padre de los ángeles, flotando con una serenidad absoluta que roza lo divino.", room: "universo_dragon_ball", tags: ["dios", "imponente", "tranquilo"], favoritePlace: "palacio_zeno", universo: "Universo Dragon Ball", hp: 1000, fuerza: 200, defensa: 200, mana: 300, alineacion: "Neutral", habilidadEspecial: "Creación Multiversal" },

    // Naruto
    naruto_uzumaki: { id: "naruto_uzumaki", name: "Naruto Uzumaki", desc: "El Ninja de la Hoja con su traje naranja y la banda de Hokage. Desborda energía.", room: "universo_shonen_jump", tags: ["alegre", "heroico", "determinado", "lider"], favoritePlace: "restaurante_ramen", universo: "Universo Naruto", hp: 380, fuerza: 70, defensa: 60, mana: 120, alineacion: "Heroe", habilidadEspecial: "Rasengan Gigante" },
    sasuke_uchiha: { id: "sasuke_uchiha", name: "Sasuke Uchiha", desc: "El último ninja Uchiha con la capa negra, manteniendo su Sharingan activo.", room: "universo_shonen_jump", tags: ["edgy", "serio", "antiheroe", "mago"], favoritePlace: "valle_del_fin", universo: "Universo Naruto", hp: 370, fuerza: 68, defensa: 58, mana: 125, alineacion: "Antiheroe", habilidadEspecial: "Chidori Kagutsuchi" },
    kakashi_hatake: { id: "kakashi_hatake", name: "Kakashi Hatake", desc: "El Ninja Copia leyendo su libro de Icha Icha con la banda inclinada en su ojo.", room: "universo_shonen_jump", tags: ["sabio_serio", "tranquilo", "estratega", "heroico"], favoritePlace: "monumento_hokage", universo: "Universo Naruto", hp: 280, fuerza: 48, defensa: 40, mana: 90, alineacion: "Heroe", habilidadEspecial: "Kamui" },
    itachi_uchiha: { id: "itachi_uchiha", name: "Itachi Uchiha", desc: "El prodigio con la capa de Akatsuki y cuervos revoloteando a su alrededor.", room: "universo_shonen_jump", tags: ["edgy", "sabio_serio", "trágico", "mago"], favoritePlace: "cueva_akatsuki", universo: "Universo Naruto", hp: 300, fuerza: 52, defensa: 45, mana: 130, alineacion: "Antiheroe", habilidadEspecial: "Tsukuyomi" },
    madara_uchiha: { id: "madara_uchiha", name: "Madara Uchiha", desc: "El legendario fundador del clan Uchiha con su armadura roja de placas.", room: "universo_shonen_jump", tags: ["villano", "imponente", "orgulloso"], favoritePlace: "cruz_de_guerra", universo: "Universo Naruto", hp: 490, fuerza: 88, defensa: 80, mana: 140, alineacion: "Villano", habilidadEspecial: "Meteorito Susanoo" },
    minato_namikaze: { id: "minato_namikaze", name: "Minato Namikaze", desc: "El Rayo Amarillo de la Hoja con su capa blanca flotando al instante.", room: "universo_shonen_jump", tags: ["heroico", "tranquilo", "lider", "agil"], favoritePlace: "bosque_hoja", universo: "Universo Naruto", hp: 320, fuerza: 58, defensa: 42, mana: 110, alineacion: "Heroe", habilidadEspecial: "Dios del Trovador Volador" },
    gaara: { id: "gaara", name: "Gaara del Desierto", desc: "El Kazekage con su enorme calabaza de arena cargada a la espalda.", room: "universo_shonen_jump", tags: ["serio", "protector", "heroico", "lider"], favoritePlace: "azotea_suna", universo: "Universo Naruto", hp: 310, fuerza: 50, defensa: 75, mana: 95, alineacion: "Heroe", habilidadEspecial: "Ataúd de Arena" },
    shikamaru_nara: { id: "shikamaru_nara", name: "Shikamaru Nara", desc: "El estratega perezoso mirando las nubes mientras piensa mil jugadas.", room: "universo_shonen_jump", tags: ["analitico", "perezoso", "estrategا"], favoritePlace: "colina_de_las_nubes", universo: "Universo Naruto", hp: 180, fuerza: 20, defensa: 22, mana: 85, alineacion: "Heroe", habilidadEspecial: "Posesión de Sombras" },
    jiraiya: { id: "jiraiya", name: "Jiraiya (El Sabio de los Sapos)", desc: "El ermitaño sabio sonriendo sobre un sapo gigante mientras escribe sus novelas.", room: "universo_shonen_jump", tags: ["sabio_serio", "comico", "heroico"], favoritePlace: "aguas_termales", universo: "Universo Naruto", hp: 340, fuerza: 62, defensa: 50, mana: 105, alineacion: "Heroe", habilidadEspecial: "Rasengan de Modo Sabio" },
    orochimaru: { id: "orochimaru", name: "Orochimaru", desc: "El Sannin serpiente de piel pálida y ojos amarillos rasgados.", room: "universo_shonen_jump", tags: ["villano", "mysterioso", "cientifico"], favoritePlace: "laboratorio_subterraneo", universo: "Universo Naruto", hp: 330, fuerza: 55, defensa: 48, mana: 115, alineacion: "Villano", habilidadEspecial: "Invocacion Manda" },
    pain_nagato: { id: "pain_nagato", name: "Pain (Nagato)", desc: "El líder de Akatsuki con sus piercings negros y el Rinnegan en los ojos.", room: "universo_shonen_jump", tags: ["villano", "divino", "trágico"], favoritePlace: "torre_lluvia", universo: "Universo Naruto", hp: 400, fuerza: 72, defensa: 60, mana: 135, alineacion: "Villano", habilidadEspecial: "Shinra Tensei" },

    // Fairy Tail
    natsu_dragneel: { id: "natsu_dragneel", name: "Natsu Dragneel", desc: "El Mago de Fairy Tail con su bufanda de escamas. Le salen chispas de fuego de los puños.", room: "universo_shonen_jump", tags: ["alegre", "caotico", "competitivo", "impulsivo"], favoritePlace: "coliseo_gladiadores", universo: "Universo Fairy Tail", hp: 330, fuerza: 65, defensa: 45, mana: 90, alineacion: "Heroe", habilidadEspecial: "Rugido del Dragon de Fuego" },
    gray_fullbuster: { id: "gray_fullbuster", name: "Gray Fullbuster", desc: "El mago de hielo caminando distraído sin camisa por costumbre.", room: "universo_shonen_jump", tags: ["serio", "heroico", "competitivo"], favoritePlace: "pista_hielo", universo: "Universo Fairy Tail", hp: 320, fuerza: 62, defensa: 48, mana: 88, alineacion: "Heroe", habilidadEspecial: "Ice-Make: Lanza" },
    sting_eucliffe: { id: "sting_eucliffe", name: "Sting Eucliffe", desc: "El Dragon Slayer Blanco de Sabertooth lucen una sonrisa confiada.", room: "universo_shonen_jump", tags: ["orgulloso", "heroico", "joven"], favoritePlace: "gremio_sabertooth", universo: "Universo Fairy Tail", hp: 290, fuerza: 56, defensa: 40, mana: 80, alineacion: "Heroe", habilidadEspecial: "Garra del Dragón Blanco" },
    laxus_dreyar: { id: "laxus_dreyar", name: "Laxus Dreyar", desc: "El imponente mago de rayo con auriculares gigantes y abrigo al hombro.", room: "universo_shonen_jump", tags: ["fuerza_bruta", "orgulloso", "heroico"], favoritePlace: "barra_gremio", universo: "Universo Fairy Tail", hp: 380, fuerza: 74, defensa: 62, mana: 95, alineacion: "Heroe", habilidadEspecial: "Alabarda del Dragón del Rayo" },
    zeref_dragneel: { id: "zeref_dragneel", name: "Zeref Dragneel", desc: "El mago oscuro inmortal vistiendo túnica negra con mirada melancólica.", room: "universo_shonen_jump", tags: ["villano", "trágico", "mago"], favoritePlace: "imperio_alvarez", universo: "Universo Fairy Tail", hp: 450, fuerza: 70, defensa: 80, mana: 160, alineacion: "Villano", habilidadEspecial: "Onda de Magia Negra" },

    // My Hero Academia
    midoriya_izuku: { id: "midoriya_izuku", name: "Izuku Midoriya (Deku)", desc: "El heredero del One For All con su traje verde de héroe y su libreta de notas.", room: "universo_shonen_jump", tags: ["heroico", "analitico", "alegre", "determinado"], favoritePlace: "gimnasio_alto_rendimiento", universo: "Universo My Hero Academia", hp: 290, fuerza: 62, defensa: 40, mana: 70, alineacion: "Heroe", habilidadEspecial: "Delaware Detroit Smash" },
    katsuki_bakugo: { id: "katsuki_bakugo", name: "Katsuki Bakugo", desc: "El explosivo héroe con guantes en forma de granada gritando '¡SHINE!'", room: "universo_shonen_jump", tags: ["agresivo", "competitivo", "orgulloso", "heroico"], favoritePlace: "campo_explosiones", universo: "Universo My Hero Academia", hp: 280, fuerza: 60, defensa: 38, mana: 65, alineacion: "Heroe", habilidadEspecial: "Impacto de Obús" },
    shoto_todoroki: { id: "shoto_todoroki", name: "Shoto Todoroki", desc: "El joven de cabello bicolor capaz de controlar el hielo y el fuego simultáneamente.", room: "universo_shonen_jump", tags: ["serio", "heroico", "tranquilo"], favoritePlace: "dojo_familiar", universo: "Universo My Hero Academia", hp: 270, fuerza: 58, defensa: 42, mana: 85, alineacion: "Heroe", habilidadEspecial: "Muro de Hielo Flameante" },
    all_might: { id: "all_might", name: "All Might (Toshinori Yagi)", desc: "El Símbolo de la Paz con su sonrisa impecable y musculatura dorada.", room: "universo_shonen_jump", tags: ["heroico", "lider", "fuerza_bruta", "inspirador"], favoritePlace: "agencia_heroes", universo: "Universo My Hero Academia", hp: 450, fuerza: 92, defensa: 75, mana: 50, alineacion: "Heroe", habilidadEspecial: "United States of Smash" },
    endeavor: { id: "endeavor", name: "Endeavor (Enji Todoroki)", desc: "El Héroe Número Uno rodeado por una barba y antifaz de llamas ardientes.", room: "universo_shonen_jump", tags: ["serio", "agresivo", "heroico", "lider"], favoritePlace: "agencia_endeavor", universo: "Universo My Hero Academia", hp: 360, fuerza: 72, defensa: 55, mana: 80, alineacion: "Heroe", habilidadEspecial: "Prominence Burn" },
    hawks: { id: "hawks", name: "Hawks (Keigo Takami)", desc: "El héroe de alas rojas pluma a pluma comiendo pollo frito relajadamente.", room: "universo_shonen_jump", tags: ["alegre", "agil", "estrategا", "heroico"], favoritePlace: "cielo_ciudad", universo: "Universo My Hero Academia", hp: 220, fuerza: 38, defensa: 25, mana: 75, alineacion: "Heroe", habilidadEspecial: "Cuchillas de Pluma" },
    dabi: { id: "dabi", name: "Dabi (Toya Todoroki)", desc: "El villano repleto de grapas en la piel emanando intensas llamas azules.", room: "universo_shonen_jump", tags: ["villano", "edgy", "caotico"], favoritePlace: "callejon_quemado", universo: "Universo My Hero Academia", hp: 250, fuerza: 64, defensa: 20, mana: 90, alineacion: "Villano", habilidadEspecial: "Llama Azul Infernal" },
    shigaraki: { id: "shigaraki", name: "Tomura Shigaraki", desc: "El líder de la Liga de Villanos rascándose el cuello con desprecio por la sociedad.", room: "universo_shonen_jump", tags: ["villano", "caotico", "destructivo"], favoritePlace: "guarida_subterranea", universo: "Universo My Hero Academia", hp: 320, fuerza: 68, defensa: 45, mana: 80, alineacion: "Villano", habilidadEspecial: "Deterioro Total" },

    // Fire Force
    shinra_kusakabe: { id: "shinra_kusakabe", name: "Shinra Kusakabe", desc: "El Oficial de la Fire Force. Muestra su sonrisa diabólica mientras sus pies botan llamas.", room: "universo_shonen_jump", tags: ["heroico", "misentendido", "determinado", "agresivo"], favoritePlace: "pista_patinaje", universo: "Universo Fire Force", hp: 280, fuerza: 58, defensa: 35, mana: 70, alineacion: "Heroe", habilidadEspecial: "Patada del Demonio" },
    arthur_boyle: { id: "arthur_boyle", name: "Arthur Boyle", desc: "El Caballero Rey sosteniendo su espada de plasma Excalibur creyéndose en la Edad Media.", room: "universo_shonen_jump", tags: ["comico", "heroico", "excentrico"], favoritePlace: "castillo_imaginario", universo: "Universo Fire Force", hp: 270, fuerza: 56, defensa: 36, mana: 60, alineacion: "Heroe", habilidadEspecial: "Corte Excalibur" },
    benimaru: { id: "benimaru", name: "Benimaru Shinmon", desc: "El oficial más fuerte de Asakusa con pupilas en forma de 'X' y 'O'.", room: "universo_shonen_jump", tags: ["fuerte", "tranquilo", "lider", "heroico"], favoritePlace: "distrito_asakusa", universo: "Universo Fire Force", hp: 420, fuerza: 86, defensa: 70, mana: 100, alineacion: "Heroe", habilidadEspecial: "Sun Wheel Kagutsuchi" },
    joker_ff: { id: "joker_ff", name: "Joker (Fire Force)", desc: "El antihéroe de parche en el ojo arrojando cartas encendidas en humo.", room: "universo_shonen_jump", tags: ["antiheroe", "misterioso", "caotico"], favoritePlace: "sombras_calle", universo: "Universo Fire Force", hp: 300, fuerza: 54, defensa: 40, mana: 85, alineacion: "Antiheroe", habilidadEspecial: "Naipes de Fuego" },

    // Fate
    shirou_emiya: { id: "shirou_emiya", name: "Shirou Emiya", desc: "Un joven de cabello pelirrojo listo para proyectar espadas si es necesario.", room: "universo_anime_variado", tags: ["heroico", "serio", "altruista", "determinado"], favoritePlace: "restaurante_lujoso", universo: "Universo Fate", hp: 220, fuerza: 35, defensa: 28, mana: 90, alineacion: "Heroe", habilidadEspecial: "Trace On: Kanshou y Bakuya" },
    archer_emiya: { id: "archer_emiya", name: "Archer (EMIYA)", desc: "El Servant de manto rojo y cabello blanco observando con cinismo.", room: "universo_anime_variado", tags: ["edgy", "sarcastico", "antiheroe", "estrategا"], favoritePlace: "colina_de_espadas", universo: "Universo Fate", hp: 310, fuerza: 54, defensa: 42, mana: 120, alineacion: "Antiheroe", habilidadEspecial: "Unlimited Blade Works" },
    gilgamesh: { id: "gilgamesh", name: "Gilgamesh", desc: "El Rey de los Héroes en armadura dorada mirándote como a un mestizo insignificante.", room: "universo_anime_variado", tags: ["orgulloso", "villano", "mago", "dios"], favoritePlace: "sala_del_tesoro", universo: "Universo Fate", hp: 380, fuerza: 68, defensa: 55, mana: 150, alineacion: "Villano", habilidadEspecial: "Gate of Babylon" },
    cu_chulainn: { id: "cu_chulainn", name: "Lancer (Cú Chulainn)", desc: "El lancero irlandés azul portando a Gáe Bulg con postura relajada.", room: "universo_anime_variado", tags: ["heroico", "agil", "luchador"], favoritePlace: "muelle_pesca", universo: "Universo Fate", hp: 290, fuerza: 52, defensa: 38, mana: 70, alineacion: "Heroe", habilidadEspecial: "Gáe Bulg" },
    iskandar: { id: "iskandar", name: "Rider (Iskandar)", desc: "El Rey de los Conquistadores, un gigante peli-rojo de capa capa roja y gran risa.", room: "universo_anime_variado", tags: ["lider", "heroico", "fuerza_bruta", "carismatico"], favoritePlace: "campo_abierto", universo: "Universo Fate", hp: 400, fuerza: 75, defensa: 60, mana: 90, alineacion: "Heroe", habilidadEspecial: "Ionioi Hetairoi" },

    // SAO
    kirito_kazuto: { id: "kirito_kazuto", name: "Kirito (Kazuto Kirigaya)", desc: "El Espadachín Negro, vistiendo su abrigo oscuro y con su fiel espada.", room: "universo_anime_variado", tags: ["edgy", "tranquilo", "gamer", "heroico"], favoritePlace: "arcade_retro", universo: "Universo SAO", hp: 260, fuerza: 48, defensa: 35, mana: 60, alineacion: "Heroe", habilidadEspecial: "Starburst Stream" },
    eugeo: { id: "eugeo", name: "Eugeo", desc: "El joven caballero con la Espada de la Rosa Azul al cinto.", room: "universo_anime_variado", tags: ["heroico", "tranquilo", "leal"], favoritePlace: "bosque_central", universo: "Universo SAO", hp: 240, fuerza: 44, defensa: 36, mana: 70, alineacion: "Heroe", habilidadEspecial: "Enhance Arm: Blue Rose" },
    klein: { id: "klein", name: "Klein (Ryoutarou Tsuboi)", desc: "El líder del gremio Fuurinkazan empuñando su katana con pañuelo rojo.", room: "universo_anime_variado", tags: ["alegre", "comico", "leal"], favoritePlace: "taberna_virtual", universo: "Universo SAO", hp: 220, fuerza: 38, defensa: 30, mana: 40, alineacion: "Heroe", habilidadEspecial: "Corte de Katana Ignea" },

    // Toaru / Escolar
    kamijou_touma: { id: "kamijou_touma", name: "Kamijou Touma", desc: "Un estudiante de secundaria con el pelo erizado y gesto de profunda resignación.", room: "universo_anime_variado", tags: ["heroico", "desafortunado", "alegre", "humilde"], favoritePlace: "puesto_comida_callejera", universo: "Universo Toaru", hp: 170, fuerza: 20, defensa: 15, mana: 0, alineacion: "Heroe", habilidadEspecial: "Imagine Breaker" },
    accelerator: { id: "accelerator", name: "Accelerator", desc: "El esper número uno de Ciudad Academia con cabello blanco y muleta metálica.", room: "universo_anime_variado", tags: ["antiheroe", "edgy", "orgulloso", "mago"], favoritePlace: "callejon_industrial", universo: "Universo Toaru", hp: 230, fuerza: 25, defensa: 100, mana: 130, alineacion: "Antiheroe", habilidadEspecial: "Redireccion de Vectores" },
    senpai: { id: "senpai", name: "Senpai", desc: "Un estudiante de uniforme impecable que parece sacado de una novela visual escolar.", room: "universo_anime_variado", tags: ["tranquilo", "amigable", "ordinario"], favoritePlace: "cafe_gourmet", universo: "Escolar", hp: 100, fuerza: 8, defensa: 5, mana: 10, alineacion: "Neutral", habilidadEspecial: "Encanto de Protagonista" },
    tadano: { id: "tadano", name: "Tadano Hitohito", desc: "Un estudiante de secundaria promedio capaz de leer el ambiente a la perfección.", room: "universo_anime_variado", tags: ["analitico", "humilde", "amigable"], favoritePlace: "salon_clases", universo: "Escolar", hp: 105, fuerza: 10, defensa: 10, mana: 20, alineacion: "Heroe", habilidadEspecial: "Lectura del Ambiente" },

    // Hazbin / Helluva Boss
    blitzo: { id: "blitzo", name: "Blitzo (I.M.P.)", desc: "Un imp rojo de cuernos a rayas con su traje de negocios desgastado y una sonrisa maniaca.", room: "universo_hazbin_helluva", tags: ["caotico", "comico", "agresivo", "mercenario"], favoritePlace: "club_gay_striptease", universo: "Hazbin / Helluva", hp: 190, fuerza: 30, defensa: 18, mana: 40, alineacion: "Caotico", habilidadEspecial: "Disparo de Francotirador" },
    moxxie: { id: "moxxie", name: "Moxxie (I.M.P.)", desc: "Un pequeño demonio imp especialista en armas, revisando obsesivamente sus mapas y pistolas.", room: "universo_hazbin_helluva", tags: ["serio", "analitico", "nervioso", "mercenario"], favoritePlace: "teatro_opera", universo: "Hazbin / Helluva", hp: 160, fuerza: 24, defensa: 15, mana: 30, alineacion: "Neutral", habilidadEspecial: "Disparo de Precision" },
    andrealphus: { id: "andrealphus", name: "Andrealphus", desc: "El demonio pavo real de escarcha con modos refinados y desprecio hacia los imps.", room: "universo_hazbin_helluva", tags: ["elegante", "mago", "frio"], favoritePlace: "palacio_hielo", universo: "Hazbin / Helluva", hp: 260, fuerza: 32, defensa: 40, mana: 110, alineacion: "Villano", habilidadEspecial: "Ráfaga Helada Goetia" },
    vortex: { id: "vortex", name: "Vortex", desc: "Un enorme sabueso del infierno musculoso trabajando de guardaespaldas VIP.", room: "universo_hazbin_helluva", tags: ["fuerza_bruta", "tranquilo", "guardaespaldas"], favoritePlace: "fiesta_infernal", universo: "Hazbin / Helluva", hp: 280, fuerza: 50, defensa: 35, mana: 20, alineacion: "Neutral", habilidadEspecial: "Tacleada Canina" },
    vassago: { id: "vassago", name: "Vassago", desc: "Un príncipe demonio ave con plumas rojas vibrantes y actitud despreocupada.", room: "universo_hazbin_helluva", tags: ["excentrico", "mago", "elegante"], favoritePlace: "salon_goetia", universo: "Hazbin / Helluva", hp: 250, fuerza: 30, defensa: 35, mana: 100, alineacion: "Neutral", habilidadEspecial: "Revelación Divinatoria" },
    angel_dust: { id: "angel_dust", name: "Angel Dust", desc: "La estrella demonio araña con seis brazos sosteniendo subametralladoras Tommys.", room: "universo_hazbin_helluva", tags: ["alegre", "caotico", "comico"], favoritePlace: "estudio_grabacion", universo: "Hazbin / Helluva", hp: 180, fuerza: 28, defensa: 16, mana: 50, alineacion: "Antiheroe", habilidadEspecial: "Lluvia de Plomo Ametralladora" },
    valentino: { id: "valentino", name: "Valentino", desc: "El overlord polilla con gafas delgadas y capa de humo rosa manipuladora.", room: "universo_hazbin_helluva", tags: ["villano", "agresivo", "manipulador"], favoritePlace: "estudio_pornografico", universo: "Hazbin / Helluva", hp: 270, fuerza: 40, defensa: 30, mana: 85, alineacion: "Villano", habilidadEspecial: "Humo de Pheromonas" },
    vox: { id: "vox", name: "Vox", desc: "El overlord televisión con cabeza de pantalla plana emitiendo interferencia eléctrica.", room: "universo_hazbin_helluva", tags: ["villano", "tecnologico", "ambicioso"], favoritePlace: "estudio_tv", universo: "Hazbin / Helluva", hp: 290, fuerza: 38, defensa: 38, mana: 105, alineacion: "Villano", habilidadEspecial: "Rayo de Señal Electrica" },
    san_pedro: { id: "san_pedro", name: "San Pedro", desc: "El guardián angelical del cielo cantando con voz aguda en las puertas doradas.", room: "universo_hazbin_helluva", tags: ["divino", "alegre", "ordinario"], favoritePlace: "puertas_cielo", universo: "Hazbin / Helluva", hp: 200, fuerza: 15, defensa: 30, mana: 90, alineacion: "Heroe", habilidadEspecial: "Canto Celestial" },
    stolas: { id: "stolas", name: "Príncipe Stolas", desc: "Un alto y elegante demonio búho de la Goetia con túnica real y ojos llenos de misterio.", room: "universo_hazbin_helluva", tags: ["dramatico", "elegante", "mago", "cariñoso"], favoritePlace: "mirador_estrellas", universo: "Hazbin / Helluva", hp: 310, fuerza: 35, defensa: 40, mana: 140, alineacion: "Neutral", habilidadEspecial: "Mirada de Piedra Estelar" },
    alastor: { id: "alastor", name: "Alastor (El Demonio de la Radio)", desc: "Una figura esbelta con traje rojo, orejas de ciervo y una sonrisa inquietante constante.", room: "universo_hazbin_helluva", tags: ["caotico", "elegante", "misterioso", "peligroso"], favoritePlace: "teatro_opera", universo: "Hazbin / Helluva", hp: 380, fuerza: 60, defensa: 50, mana: 130, alineacion: "Caotico", habilidadEspecial: "Sombras Radiomórficas" },
    lucifer: { id: "lucifer", name: "Lucifer Morningstar", desc: "El Rey del Infierno vistiendo un elegante traje blanco con sombrero de copa y bastón.", room: "universo_hazbin_helluva", tags: ["alegre", "excentrico", "dramatico", "poderoso"], favoritePlace: "parque_atracciones", universo: "Hazbin / Helluva", hp: 500, fuerza: 85, defensa: 80, mana: 160, alineacion: "Antiheroe", habilidadEspecial: "Poder del Pecado Original" },
    husk: { id: "husk", name: "Husk", desc: "El demonio gato alado con cartas de póquer y una botella de barato alcohol.", room: "universo_hazbin_helluva", tags: ["sarcastico", "perezoso", "barman"], favoritePlace: "barra_hotel", universo: "Hazbin / Helluva", hp: 210, fuerza: 30, defensa: 22, mana: 60, alineacion: "Neutral", habilidadEspecial: "Tiro de Naipes Explosivos" },
    sir_pentious: { id: "sir_pentious", name: "Sir Pentious", desc: "El inventor cobras serpiente victoriano con su dirigible y sus Egg Bois.", room: "universo_hazbin_helluva", tags: ["comico", "inventor", "heroico"], favoritePlace: "taller_dirigible", universo: "Hazbin / Helluva", hp: 220, fuerza: 26, defensa: 28, mana: 70, alineacion: "Heroe", habilidadEspecial: "Disparo de Rayo Laser" },
    adam: { id: "adam", name: "Adam (Líder Exterminador)", desc: "El primer hombre con su guitarra eléctrica dorada y túnica de ángel exterminador.", room: "universo_hazbin_helluva", tags: ["villano", "egocentrico", "divino"], favoritePlace: "escenario_cielo", universo: "Hazbin / Helluva", hp: 420, fuerza: 78, defensa: 65, mana: 100, alineacion: "Villano", habilidadEspecial: "Riff Sagrado Destructivo" },
    razzle_dazzle: { id: "razzle_dazzle", name: "Razzle y Dazzle", desc: "Los dos pequeños dragones demonios guardianes de Charlie.", room: "universo_hazbin_helluva", tags: ["amigable", "monstruo", "protector"], favoritePlace: "hotel_hazbin", universo: "Hazbin / Helluva", hp: 240, fuerza: 35, defensa: 30, mana: 50, alineacion: "Heroe", habilidadEspecial: "Soplido de Fuego Combinado" },

    // Sonic
    sonic: { id: "sonic", name: "Sonic el Erizo", desc: "El erizo azul más rápido del mundo, dando golpecitos en el suelo con su zapatilla.", room: "universo_sega_sonic", tags: ["alegre", "heroico", "confiado", "hiperactivo"], favoritePlace: "parque_atracciones", universo: "Universo Sonic", hp: 250, fuerza: 40, defensa: 28, mana: 80, alineacion: "Heroe", habilidadEspecial: "Spin Dash" },
    shadow: { id: "shadow", name: "Shadow el Erizo", desc: "La Forma de Vida Suprema. Se mantiene cruzado de brazos con aura de energía oscura.", room: "universo_sega_sonic", tags: ["edgy", "solitario", "serio", "antiheroe"], favoritePlace: "bar_subterraneo", universo: "Universo Sonic", hp: 280, fuerza: 50, defensa: 35, mana: 95, alineacion: "Antiheroe", habilidadEspecial: "Chaos Blast" },
    silver: { id: "silver", name: "Silver el Erizo", desc: "El erizo plateado del futuro flotando con aura telequinética brillante.", room: "universo_sega_sonic", tags: ["heroico", "tranquilo", "mago"], favoritePlace: "futuro_ruinas", universo: "Universo Sonic", hp: 240, fuerza: 32, defensa: 30, mana: 110, alineacion: "Heroe", habilidadEspecial: "Psicoquinesis" },
    knuckles: { id: "knuckles", name: "Knuckles the Echidna", desc: "El guardián de la Esmeralda Maestra, apretando sus puños con púas.", room: "universo_sega_sonic", tags: ["serio", "orgulloso", "protector", "fuerza_bruta"], favoritePlace: "templo_antiguo", universo: "Universo Sonic", hp: 290, fuerza: 58, defensa: 42, mana: 30, alineacion: "Heroe", habilidadEspecial: "Puñetazo Sísmico" },
    tails: { id: "tails", name: "Tails (Miles Prower)", desc: "El zorro de dos colas volando con su tableta científica en mano.", room: "universo_sega_sonic", tags: ["inventor", "heroico", "joven"], favoritePlace: "taller_aviones", universo: "Universo Sonic", hp: 180, fuerza: 20, defensa: 20, mana: 80, alineacion: "Heroe", habilidadEspecial: "Bomba de Pulso" },
    eggman: { id: "eggman", name: "Dr. Eggman (Robtnik)", desc: "El científico villano en su Egg Mobile acariciándose el enorme bigote.", room: "universo_sega_sonic", tags: ["villano", "inventor", "egocentrico"], favoritePlace: "eggmanland", universo: "Universo Sonic", hp: 220, fuerza: 15, defensa: 50, mana: 60, alineacion: "Villano", habilidadEspecial: "Invocación de Mech" },
    zazz: { id: "zazz", name: "Zazz (Zeti)", desc: "Un alienígena rosado y frenético con cuernos, riéndose salvajemente.", room: "universo_sega_sonic", tags: ["caotico", "agresivo", "maniaco", "enemigo"], favoritePlace: "concierto_rock", universo: "Universo Sonic", hp: 230, fuerza: 42, defensa: 22, mana: 30, alineacion: "Villano", habilidadEspecial: "Ataque Estrellado" },
    vector: { id: "vector", name: "Vector the Crocodile", desc: "El cocodrilo detective con audífonos gigantes buscando dinero de clientes.", room: "universo_sega_sonic", tags: ["comico", "detective", "fuerza_bruta"], favoritePlace: "agencia_chaotix", universo: "Universo Sonic", hp: 270, fuerza: 48, defensa: 35, mana: 20, alineacion: "Heroe", habilidadEspecial: "Mordisco Cocodrilo" },
    espio: { id: "espio", name: "Espio the Chameleon", desc: "El ninja camaleón morado cruzado de brazos en perfecta invisibilidad.", room: "universo_sega_sonic", tags: ["serio", "ninja", "agil"], favoritePlace: "dojo_sombra", universo: "Universo Sonic", hp: 210, fuerza: 34, defensa: 25, mana: 70, alineacion: "Heroe", habilidadEspecial: "Shuriken Sigiloso" },

    // Capcom
    leon_kennedy_re2: { id: "leon_kennedy_re2", name: "Leon S. Kennedy (RE2)", desc: "Un agente novato con el uniforme táctico del R.P.D., sosteniendo su linterna con firmeza.", room: "universo_capcom_resident", tags: ["heroico", "inocente", "superviviente", "determinado"], favoritePlace: "puesto_comida_callejera", universo: "Universo Capcom", hp: 180, fuerza: 25, defensa: 18, mana: 30, alineacion: "Heroe", habilidadEspecial: "Disparo Matilda" },
    leon_kennedy_re4: { id: "leon_kennedy_re4", name: "Leon S. Kennedy (RE4)", desc: "El agente veterano del gobierno con su campera de cuero marrón, manteniendo la calma.", room: "universo_capcom_resident", tags: ["sarcastico", "serio", "heroico", "superviviente"], favoritePlace: "bar_subterraneo", universo: "Universo Capcom", hp: 240, fuerza: 38, defensa: 28, mana: 40, alineacion: "Heroe", habilidadEspecial: "Patada Giro Supina" },
    chris_redfield: { id: "chris_redfield", name: "Chris Redfield", desc: "Un musculoso veterano armado hasta los dientes con equipo táctico pesado.", room: "universo_capcom_resident", tags: ["serio", "militar", "heroico", "protector"], favoritePlace: "campo_tiro", universo: "Universo Capcom", hp: 270, fuerza: 48, defensa: 35, mana: 20, alineacion: "Heroe", habilidadEspecial: "Puñetazo a Roca" },
    mega_man: { id: "mega_man", name: "Mega Man (Rock)", desc: "El robot azul con su Mega Buster cargado y listo en su brazo derecho.", room: "universo_capcom_resident", tags: ["heroico", "alegre", "justiciero", "noble"], favoritePlace: "museo_tecnologico", universo: "Universo Capcom", hp: 250, fuerza: 40, defensa: 32, mana: 80, alineacion: "Heroe", habilidadEspecial: "Mega Buster Cargado" },
    wesker: { id: "wesker", name: "Albert Wesker", desc: "El ex-lider de S.T.A.R.S. con gafas oscuras de noche y poderes del virus Uroboros.", room: "universo_capcom_resident", tags: ["villano", "estrategا", "agil"], favoritePlace: "laboratorio_umbrella", universo: "Universo Capcom", hp: 350, fuerza: 65, defensa: 50, mana: 60, alineacion: "Villano", habilidadEspecial: "Movimiento Teleport Cobra" },
    nemesis: { id: "nemesis", name: "Nemesis (T-Type)", desc: "La B.O.W. gigante envuelta en cuero negro gruñendo 'STARS...' con su lanzacohetes.", room: "universo_capcom_resident", tags: ["monstruo", "fuerza_bruta", "villano"], favoritePlace: "calle_raccoon_city", universo: "Universo Capcom", hp: 450, fuerza: 82, defensa: 65, mana: 0, alineacion: "Villano", habilidadEspecial: "Impacto de Lanzacohetes" },
    krauser: { id: "krauser", name: "Jack Krauser", desc: "El mercenario ex-camarada con boina roja y brazo mutado en cuchilla orgánica.", room: "universo_capcom_resident", tags: ["mercenario", "villano", "militar"], favoritePlace: "ruinas_isla", universo: "Universo Capcom", hp: 310, fuerza: 58, defensa: 45, mana: 20, alineacion: "Villano", habilidadEspecial: "Corte de Brazo Mutado" },
    luis_sera: { id: "luis_sera", name: "Luis Sera", desc: "El carismático ex-investigador madrileño fumando un cigarrillo con guitarrón.", room: "universo_capcom_resident", tags: ["carismatico", "comico", "heroico"], favoritePlace: "mina_pueblo", universo: "Universo Capcom", hp: 170, fuerza: 22, defensa: 15, mana: 20, alineacion: "Heroe", habilidadEspecial: "Disparo Red9" },
    carlos_oliveira: { id: "carlos_oliveira", name: "Carlos Oliveira", desc: "El mercenario de U.B.C.S. de melena rizada listo para rescatar a la gente.", room: "universo_capcom_resident", tags: ["heroico", "militar", "carismatico"], favoritePlace: "hospital_raccoon", universo: "Universo Capcom", hp: 220, fuerza: 34, defensa: 25, mana: 20, alineacion: "Heroe", habilidadEspecial: "Ráfaga de Asalto" },
    m_bison: { id: "m_bison", name: "M. Bison (Vega)", desc: "El líder de Shadaloo envuelto en Psycho Power de aura purpura.", room: "universo_capcom_resident", tags: ["villano", "imponente", "mago"], favoritePlace: "base_shadaloo", universo: "Universo Capcom", hp: 380, fuerza: 72, defensa: 55, mana: 100, alineacion: "Villano", habilidadEspecial: "Psycho Crusher" },

    // Darkstalkers
    jontalbain: { id: "jontalbain", name: "Jon Talbain", desc: "El hombre lobo luchador en su traje de artes marciales blanco.", room: "universo_darkstalkers", tags: ["edgy", "solitario", "luchador", "serio"], favoritePlace: "dojo_artes_marciales", universo: "Darkstalkers", hp: 260, fuerza: 52, defensa: 30, mana: 40, alineacion: "Antiheroe", habilidadEspecial: "Dragon Cannon" },
    mukai: { id: "mukai", name: "Mukai", desc: "Un ser de piedra petrificada de presencia monumental, exudando aura de antigüedad.", room: "universo_darkstalkers", tags: ["sabio_serio", "imponente", "antiguo", "rival"], favoritePlace: "templo_antiguo", universo: "Darkstalkers", hp: 400, fuerza: 75, defensa: 80, mana: 60, alineacion: "Villano", habilidadEspecial: "Petrificacion Terrestre" },
    demitri: { id: "demitri", name: "Demitri Maximoff", desc: "El lord vampiro con su abrigo elegante y peinado engominado en capas.", room: "universo_darkstalkers", tags: ["villano", "elegante", "vampiro"], favoritePlace: "castillo_zvilpoghua", universo: "Darkstalkers", hp: 330, fuerza: 60, defensa: 45, mana: 90, alineacion: "Villano", habilidadEspecial: "Midnight Bliss" },
    bishamon: { id: "bishamon", name: "Bishamon", desc: "El samurái fantasma poseído por la armadura maldita Hannya.", room: "universo_darkstalkers", tags: ["villano", "samurai", "fantasma"], favoritePlace: "templo_maldito", universo: "Darkstalkers", hp: 290, fuerza: 58, defensa: 40, mana: 50, alineacion: "Villano", habilidadEspecial: "Corte de Alma" },
    victor_darkstalkers: { id: "victor_darkstalkers", name: "Victor von Gerdenheim", desc: "El monstruo de Frankenstein con generadores eléctricos en los hombros.", room: "universo_darkstalkers", tags: ["fuerza_bruta", "monstruo", "humilde"], favoritePlace: "laboratorio_profesor", universo: "Darkstalkers", hp: 360, fuerza: 68, defensa: 50, mana: 30, alineacion: "Heroe", habilidadEspecial: "Descarga Electrica Body" },

   // Nintendo (Continuación)
    waluigi: { id: "waluigi", name: "Waluigi", desc: "Una figura alta y flacucha vestida de morado con su bigote en punta, haciendo gestos de enojo.", room: "universo_nintendo", tags: ["caotico", "comico", "envidioso", "rival"], favoritePlace: "casino_neon", universo: "Nintendo", hp: 180, fuerza: 22, defensa: 15, mana: 40, alineacion: "Caotico", habilidadEspecial: "Pisotón Wah" },
    mario: { id: "mario", name: "Mario", desc: "El fontanero del Reino Champiñón ajustándose la gorra roja con la 'M'.", room: "universo_nintendo", tags: ["heroico", "alegre", "iconico"], favoritePlace: "castillo_peach", universo: "Nintendo", hp: 250, fuerza: 42, defensa: 30, mana: 50, alineacion: "Heroe", habilidadEspecial: "Super Salto Puño" },
    luigi: { id: "luigi", name: "Luigi", desc: "El fontanero verde temblando ligeramente mientras sostiene su aspiradora Succionaentes.", room: "universo_nintendo", tags: ["heroico", "timido", "comico"], favoritePlace: "mansion_embrujada", universo: "Nintendo", hp: 230, fuerza: 38, defensa: 28, mana: 50, alineacion: "Heroe", habilidadEspecial: "Misil Verde" },
    bowser: { id: "bowser", name: "Bowser", desc: "El Rey de los Koopas rugiendo con llama ardiente en su garganta.", room: "universo_nintendo", tags: ["villano", "fuerza_bruta", "imponente"], favoritePlace: "castillo_lava", universo: "Nintendo", hp: 480, fuerza: 85, defensa: 75, mana: 60, alineacion: "Villano", habilidadEspecial: "Aliento de Fuego Gigante" },
    wario: { id: "wario", name: "Wario", desc: "El avaricioso tipo gordo de overol amarillo ríendose con bolsas de oro.", room: "universo_nintendo", tags: ["caotico", "comico", "avaricioso"], favoritePlace: "banco_oro", universo: "Nintendo", hp: 320, fuerza: 55, defensa: 45, mana: 20, alineacion: "Antiheroe", habilidadEspecial: "Tackleada de Hombro Wario" },
    pit_kid_icarus: { id: "pit_kid_icarus", name: "Pit (Kid Icarus)", desc: "El ángel guardián con sus alas blancas y su arco sagrado.", room: "universo_nintendo", tags: ["alegre", "heroico", "comelon", "leal"], favoritePlace: "buffet_libre", universo: "Nintendo", hp: 220, fuerza: 36, defensa: 25, mana: 70, alineacion: "Heroe", habilidadEspecial: "Flecha de Palutena" },
    dark_pit: { id: "dark_pit", name: "Pit Sombrío (Dark Pit)", desc: "El clon oscuro de Pit, con alas de pluma negra y una mirada desafiante.", room: "universo_nintendo", tags: ["edgy", "rebelde", "orgulloso", "antiheroe"], favoritePlace: "azotea_gothica", universo: "Nintendo", hp: 230, fuerza: 40, defensa: 26, mana: 70, alineacion: "Antiheroe", habilidadEspecial: "Báculo de Pit Sombrío" },
    link_zelda: { id: "link_zelda", name: "Link", desc: "El Héroe del Tiempo vistiendo su túnica verde, sosteniendo la Espada Maestra.", room: "universo_nintendo", tags: ["heroico", "callado", "valiente", "aventurero"], favoritePlace: "bosque_encantado", universo: "Nintendo", hp: 300, fuerza: 50, defensa: 40, mana: 80, alineacion: "Heroe", habilidadEspecial: "Giro de Espada Maestra" },
    ganondorf: { id: "ganondorf", name: "Ganondorf", desc: "El Rey del Gerudo emanando la Trifuerza del Poder con espada pesada.", room: "universo_nintendo", tags: ["villano", "imponente", "mago"], favoritePlace: "torre_gerudo", universo: "Nintendo", hp: 450, fuerza: 82, defensa: 70, mana: 100, alineacion: "Villano", habilidadEspecial: "Puño del Espectro" },
    revali: { id: "revali", name: "Revali", desc: "El altivo arquero de la tribu Rito con plumaje azul cruzado de brazos.", room: "universo_nintendo", tags: ["orgulloso", "heroico", "agil"], favoritePlace: "poblado_rito", universo: "Nintendo", hp: 200, fuerza: 38, defensa: 20, mana: 60, alineacion: "Heroe", habilidadEspecial: "Vendaval de Revali" },
    daruk: { id: "daruk", name: "Daruk", desc: "El masivo campeón Goron riendo sonoramente mientras palmea su mandoble.", room: "universo_nintendo", tags: ["fuerza_bruta", "heroico", "tanque"], favoritePlace: "ciudad_goron", universo: "Nintendo", hp: 400, fuerza: 72, defensa: 80, mana: 30, alineacion: "Heroe", habilidadEspecial: "Escudo de Daruk" },
    kass: { id: "kass", name: "Kass", desc: "El viajero Rito tocando su acordeón bajo la sombra de un árbol.", room: "universo_nintendo", tags: ["tranquilo", "músico", "sabio_serio"], favoritePlace: "posta_de_los_bosques", universo: "Nintendo", hp: 160, fuerza: 12, defensa: 18, mana: 50, alineacion: "Heroe", habilidadEspecial: "Balada Antigua" },

    // Final Fantasy / Gaming RPG
    cloud: { id: "cloud", name: "Cloud Strife", desc: "El ex-SOLDADO de pelo rubio de punta y ojos de Mako, cargando la Espada Buster.", room: "universo_gaming_rpg", tags: ["edgy", "serio", "solitario", "heroico"], favoritePlace: "bar_subterraneo", universo: "Gaming RPG", hp: 350, fuerza: 70, defensa: 50, mana: 80, alineacion: "Heroe", habilidadEspecial: "Omnilátigo" },
    sephiroth: { id: "sephiroth", name: "Sephiroth", desc: "El Ángel de Un Solo Ala empuñando la Masamune de largo descomunal.", room: "universo_gaming_rpg", tags: ["villano", "edgy", "imponente"], favoritePlace: "crater_del_norte", universo: "Gaming RPG", hp: 500, fuerza: 92, defensa: 80, mana: 130, alineacion: "Villano", habilidadEspecial: "Supernova" },
    zack_fair: { id: "zack_fair", name: "Zack Fair", desc: "El alegre SOLDADO de Primera Clase con su sonrisa contagiosa y gran Espada.", room: "universo_gaming_rpg", tags: ["heroico", "alegre", "optimista"], favoritePlace: "iglesia_slums", universo: "Gaming RPG", hp: 340, fuerza: 68, defensa: 48, mana: 75, alineacion: "Heroe", habilidadEspecial: "Corte Cadena" },
    barret: { id: "barret", name: "Barret Wallace", desc: "El líder de AVALANCHA con brazo ametralladora gritando por el planeta.", room: "universo_gaming_rpg", tags: ["heroico", "fuerza_bruta", "agresivo"], favoritePlace: "bar_seventh_heaven", universo: "Gaming RPG", hp: 380, fuerza: 65, defensa: 60, mana: 40, alineacion: "Heroe", habilidadEspecial: "Catástrofe" },
    vincent: { id: "vincent", name: "Vincent Valentine", desc: "El misterioso hombre de capa roja durmiendo en un ataúd con garra metálica.", room: "universo_gaming_rpg", tags: ["edgy", "solitario", "mysterioso"], favoritePlace: "sotano_mansion", universo: "Gaming RPG", hp: 300, fuerza: 55, defensa: 40, mana: 90, alineacion: "Antiheroe", habilidadEspecial: "Transformacion Galian Beast" },
    cid_highwind: { id: "cid_highwind", name: "Cid Highwind", desc: "El capitán piloto fumando con lanza al hombro soñando con ir al espacio.", room: "universo_gaming_rpg", tags: ["gruñon", "inventor", "heroico"], favoritePlace: "pista_cohete", universo: "Gaming RPG", hp: 290, fuerza: 58, defensa: 42, mana: 30, alineacion: "Heroe", habilidadEspecial: "Gran Salto Lanza" },
    sora: { id: "sora", name: "Sora", desc: "El portador de la Keyblade con su ropa ancha roja y negra y una sonrisa optimista.", room: "universo_gaming_rpg", tags: ["alegre", "heroico", "amigable", "optimista"], favoritePlace: "playa_tropical", universo: "Gaming RPG", hp: 280, fuerza: 52, defensa: 40, mana: 100, alineacion: "Heroe", habilidadEspecial: "Ars Arcanum" },
    riku: { id: "riku", name: "Riku", desc: "El maestro de la Keyblade de pelo plateado dominando la luz y la oscuridad.", room: "universo_gaming_rpg", tags: ["heroico", "serio", "antiheroe"], favoritePlace: "bastion_hueco", universo: "Gaming RPG", hp: 310, fuerza: 60, defensa: 45, mana: 90, alineacion: "Antiheroe", habilidadEspecial: "Dark Aura" },
    roxas: { id: "roxas", name: "Roxas", desc: "El incorpóreo portador de dos Llaves Espada (Oathkeeper y Oblivion).", room: "universo_gaming_rpg", tags: ["edgy", "heroico", "trágico"], favoritePlace: "torre_reloj_atardecer", universo: "Gaming RPG", hp: 290, fuerza: 62, defensa: 38, mana: 85, alineacion: "Heroe", habilidadEspecial: "Rayo de Dos Llaves" },
    axel_lea: { id: "axel_lea", name: "Axel (Lea)", desc: "El ex-miembro VIII lanzando sus chakrams de fuego: '¿Lo captas?'", room: "universo_gaming_rpg", tags: ["sarcastico", "heroico", "caotico"], favoritePlace: "torre_reloj_atardecer", universo: "Gaming RPG", hp: 280, fuerza: 54, defensa: 35, mana: 95, alineacion: "Heroe", habilidadEspecial: "Chakrams Incendiarios" },
    ansem: { id: "ansem", name: "Ansem (Buscador de la Oscuridad)", desc: "El sin corazón envuelto en manto con su guardián de sombras a la espalda.", room: "universo_gaming_rpg", tags: ["villano", "mysterioso", "mago"], favoritePlace: "fin_del_mundo", universo: "Gaming RPG", hp: 420, fuerza: 75, defensa: 65, mana: 120, alineacion: "Villano", habilidadEspecial: "Sumision en Oscuridad" },
    xemnas: { id: "xemnas", name: "Xemnas", desc: "El líder de la Organización XIII portando espadas de éter rojo.", room: "universo_gaming_rpg", tags: ["villano", "elegante", "lider"], favoritePlace: "mundo_que_nunca_fue", universo: "Gaming RPG", hp: 440, fuerza: 78, defensa: 68, mana: 125, alineacion: "Villano", habilidadEspecial: "Domo de Sables Eter" },

    // Crash Bandicoot
    crash: { id: "crash", name: "Crash Bandicoot", desc: "El marsupial anaranjado dando vueltas sin sentido y haciendo gestos graciosos.", room: "universo_gaming_rpg", tags: ["alegre", "caotico", "comico", "hiperactivo"], favoritePlace: "playa_tropical", universo: "Crash Bandicoot", hp: 190, fuerza: 32, defensa: 20, mana: 30, alineacion: "Heroe", habilidadEspecial: "Giro Marsupial" },
    cortex: { id: "cortex", name: "Dr. Neo Cortex", desc: "El científico de cabeza enorme con la 'N' pintada en la frente sosteniendo su pistola laser.", room: "universo_gaming_rpg", tags: ["villano", "comico", "inventor"], favoritePlace: "laboratorio_isla", universo: "Crash Bandicoot", hp: 180, fuerza: 15, defensa: 25, mana: 80, alineacion: "Villano", habilidadEspecial: "Rayo Laser de Plasma" },
    n_gin: { id: "n_gin", name: "Dr. N. Gin", desc: "El desquiciado cyborg con un misil incrustado en la cabeza.", room: "universo_gaming_rpg", tags: ["villano", "caotico", "inventor"], favoritePlace: "nave_cohete", universo: "Crash Bandicoot", hp: 170, fuerza: 12, defensa: 30, mana: 70, alineacion: "Villano", habilidadEspecial: "Lanzamiento de Mini-Misil" },
    ripper_roo: { id: "ripper_roo", name: "Ripper Roo", desc: "El canguro loco atrapado en una camisa de fuerza rebotando sobre cajas TNT.", room: "universo_gaming_rpg", tags: ["caotico", "maniaco", "comico"], favoritePlace: "cascada_locura", universo: "Crash Bandicoot", hp: 200, fuerza: 28, defensa: 15, mana: 10, alineacion: "Villano", habilidadEspecial: "Lluvia de TNT" },

    // Death Note
    light_yagami: { id: "light_yagami", name: "Light Yagami (Kira)", desc: "El estudiante de genio sosteniendo la libreta negra Death Note con sonrisa fría.", room: "universo_anime_variado", tags: ["villano", "analitico", "egocentrico"], favoritePlace: "escritorio_estudio", universo: "Death Note", hp: 110, fuerza: 10, defensa: 10, mana: 100, alineacion: "Villano", habilidadEspecial: "Escritura de Nombre" },
    ryuk: { id: "ryuk", name: "Ryuk el Shinigami", desc: "El dios de la muerte esquelético flotando pidiendo manzanas.", room: "universo_anime_variado", tags: ["caotico", "dios", "mysterioso"], favoritePlace: "mundo_shinigami", universo: "Death Note", hp: 500, fuerza: 40, defensa: 90, mana: 150, alineacion: "Neutral", habilidadEspecial: "Mirada de Shinigami" },
    l_lawliet: { id: "l_lawliet", name: "L (Lawliet)", desc: "El mejor detective del mundo encorvado descalzo comiendo terrones de azúcar.", room: "universo_anime_variado", tags: ["analitico", "sabio_serio", "heroico"], favoritePlace: "sala_investigacion", universo: "Death Note", hp: 115, fuerza: 12, defensa: 12, mana: 90, alineacion: "Heroe", habilidadEspecial: "Deduccion Impecable" },
    near: { id: "near", name: "Near (Nate River)", desc: "El joven peli-blanco jugando con dados y torres de juguetes en el suelo.", room: "universo_anime_variado", tags: ["analitico", "frio", "joven"], favoritePlace: "cuartel_spk", universo: "Death Note", hp: 100, fuerza: 8, defensa: 8, mana: 85, alineacion: "Heroe", habilidadEspecial: "Ensamblaje de Rompecabezas" },
    mello: { id: "mello", name: "Mello (Mihael Keehl)", desc: "El rebelde de chamarra de cuero mordiendo una barra de chocolate.", room: "universo_anime_variado", tags: ["rebelde", "agresivo", "competitivo"], favoritePlace: "guarida_mafia", universo: "Death Note", hp: 150, fuerza: 22, defensa: 18, mana: 50, alineacion: "Antiheroe", habilidadEspecial: "Estrategia Mafiosa" },
    teru_mikami: { id: "teru_mikami", name: "Teru Mikami", desc: "El fiscal obsesivo gritando '¡ELIMINADO!' mientras anota nombres.", room: "universo_anime_variado", tags: ["villano", "fanatico", "serio"], favoritePlace: "tribunal_justicia", universo: "Death Note", hp: 120, fuerza: 12, defensa: 10, mana: 80, alineacion: "Villano", habilidadEspecial: "Juicio Absoluto" },

    // JoJo's Bizarre Adventure
    jonathan_joestar: { id: "jonathan_joestar", name: "Jonathan Joestar", desc: "El caballero inglés masivo canalizando el Hamon en sus puños.", room: "universo_anime_variado", tags: ["heroico", "noble", "fuerza_bruta"], favoritePlace: "mansion_joestar", universo: "JoJo's Bizarre Adventure", hp: 300, fuerza: 55, defensa: 40, mana: 70, alineacion: "Heroe", habilidadEspecial: "Sunlight Yellow Overdrive" },
    joseph_joestar: { id: "joseph_joestar", name: "Joseph Joestar", desc: "El ingenioso Joestar diciendo: 'Tu siguiente línea será...'", room: "universo_anime_variado", tags: ["comico", "estrategا", "heroico"], favoritePlace: "calle_nueva_york", universo: "JoJo's Bizarre Adventure", hp: 280, fuerza: 48, defensa: 35, mana: 80, alineacion: "Heroe", habilidadEspecial: "Truco de Clackers" },
    jotaro_kujo: { id: "jotaro_kujo", name: "Jotaro Kujo", desc: "Un estudiante alto con gorra negra ajustada, invocando a Star Platinum.", room: "universo_anime_variado", tags: ["edgy", "serio", "estrategا", "heroico"], favoritePlace: "puerto_maritimo", universo: "JoJo's Bizarre Adventure", hp: 350, fuerza: 75, defensa: 55, mana: 90, alineacion: "Heroe", habilidadEspecial: "Star Platinum: Ora Ora Ora" },
    josuke_higashikata: { id: "josuke_higashikata", name: "Josuke Higashikata", desc: "El joven de Morioh protegiendo obsesivamente su peinado tupé con Crazy Diamond.", room: "universo_anime_variado", tags: ["alegre", "heroico", "orgulloso"], favoritePlace: "pueblo_morioh", universo: "JoJo's Bizarre Adventure", hp: 310, fuerza: 62, defensa: 45, mana: 80, alineacion: "Heroe", habilidadEspecial: "Crazy Diamond: Reparación" },
    kars: { id: "kars", name: "Kars", desc: "El Hombre del Pilar con espadas de luz saliendo de sus brazos.", room: "universo_anime_variado", tags: ["villano", "imponente", "antiguo"], favoritePlace: "cueva_pillar_men", universo: "JoJo's Bizarre Adventure", hp: 420, fuerza: 78, defensa: 65, mana: 90, alineacion: "Villano", habilidadEspecial: "Corte de Luz de Cuchilla" },
    wamuu: { id: "wamuu", name: "Wamuu", desc: "El noble guerrero del pilar maestro del combate con viento.", room: "universo_anime_variado", tags: ["villano", "orgulloso", "guerrero"], favoritePlace: "coliseo_romano", universo: "JoJo's Bizarre Adventure", hp: 390, fuerza: 72, defensa: 60, mana: 70, alineacion: "Villano", habilidadEspecial: "Tormenta de Arena Espiritual" },
    esidisi: { id: "esidisi", name: "Esidisi", desc: "El Hombre del Pilar experto en sangre hirviendo estallando en llanto repentino.", room: "universo_anime_variado", tags: ["villano", "excentrico", "caotico"], favoritePlace: "templo_fuego", universo: "JoJo's Bizarre Adventure", hp: 380, fuerza: 70, defensa: 58, mana: 75, alineacion: "Villano", habilidadEspecial: "Modo Fuego de Sangre" },
    dio_brando: { id: "dio_brando", name: "Dio Brando / DIO", desc: "El vampiro inmortal gritando '¡ZA WARUDO!' congelando el tiempo.", room: "universo_anime_variado", tags: ["villano", "orgulloso", "caotico", "dios"], favoritePlace: "mansion_el_cairo", universo: "JoJo's Bizarre Adventure", hp: 450, fuerza: 80, defensa: 60, mana: 110, alineacion: "Villano", habilidadEspecial: "Za Warudo: Detencion del Tiempo" },
    ultimate_kars: { id: "ultimate_kars", name: "Ultimate Kars", desc: "La Forma de Vida Definitiva con alas de pluma de águila y piel indestructible.", room: "universo_anime_variado", tags: ["villano", "dios", "imponente"], favoritePlace: "cumbre_volcanica", universo: "JoJo's Bizarre Adventure", hp: 600, fuerza: 95, defensa: 95, mana: 150, alineacion: "Villano", habilidadEspecial: "Metamorfosis de Vida Definitiva" },

    // Baki
    baki_hanma: { id: "baki_hanma", name: "Baki Hanma", desc: "El Campeón de la Arena Subterránea con la sombra del demonio en la espalda.", room: "universo_lucha_mamados", tags: ["luchador", "heroico", "fuerza_bruta"], favoritePlace: "arena_subterranea", universo: "Baki", hp: 380, fuerza: 82, defensa: 65, mana: 30, alineacion: "Heroe", habilidadEspecial: "Postura Triceratops" },
    yujiro_hanma: { id: "yujiro_hanma", name: "Yujiro Hanma (Ogro)", desc: "La Criatura Más Fuerte de la Tierra. Su sola presencia vibra el aire.", room: "universo_lucha_mamados", tags: ["imponente", "fuerza_bruta", "villano"], favoritePlace: "hotel_suite_presidencial", universo: "Baki", hp: 600, fuerza: 100, defensa: 95, mana: 50, alineacion: "Villano", habilidadEspecial: "Espalda del Demonio" },
    biscuit_oliva: { id: "biscuit_oliva", name: "Biscuit Oliva (Mr. Unchained)", desc: "El hombre más fuerte de EE.UU. flexionando masa muscular capaz de parar balas.", room: "universo_lucha_mamados", tags: ["fuerza_bruta", "tanque", "carismatico"], favoritePlace: "prision_arizona", universo: "Baki", hp: 450, fuerza: 88, defensa: 85, mana: 10, alineacion: "Neutral", habilidadEspecial: "Bola de Músculo Humana" },
    hanayama: { id: "hanayama", name: "Kaoru Hanayama", desc: "El yakuza de 19 años con el tatuaje del 'Hombre de la Pieza' en la espalda.", room: "universo_lucha_mamados", tags: ["fuerza_bruta", "noble", "yakuza"], favoritePlace: "oficina_yakuza", universo: "Baki", hp: 420, fuerza: 85, defensa: 75, mana: 0, alineacion: "Heroe", habilidadEspecial: "Pellizco Agarre Mortal" },
    doppo_orochi: { id: "doppo_orochi", name: "Doppo Orochi", desc: "El Dios del Karate de la escuela Shinshinkai en su gi blanco impecable.", room: "universo_lucha_mamados", tags: ["sabio_serio", "luchador", "disciplinado"], favoritePlace: "dojo_shinshinkai", universo: "Baki", hp: 320, fuerza: 68, defensa: 55, mana: 20, alineacion: "Heroe", habilidadEspecial: "Golpe Maewashi Geri" },
    jack_hanma: { id: "jack_hanma", name: "Jack Hanma", desc: "El canadiense gigante operado para aumentar estatura que usa la técnica del Goudou.", room: "universo_lucha_mamados", tags: ["fuerza_bruta", "agresivo", "luchador"], favoritePlace: "gimnasio_extremo", universo: "Baki", hp: 410, fuerza: 84, defensa: 70, mana: 10, alineacion: "Antiheroe", habilidadEspecial: "Mordisco Goudou" },
    retsu_kaioh: { id: "retsu_kaioh", name: "Retsu Kaioh", desc: "El maestro de Kenpo Chino de 4000 años de historia.", room: "universo_lucha_mamados", tags: ["sabio_serio", "luchador", "orgulloso"], favoritePlace: "templo_kenpo", universo: "Baki", hp: 330, fuerza: 70, defensa: 58, mana: 30, alineacion: "Heroe", habilidadEspecial: "Sunkei 4000 Años" },
    pickle: { id: "pickle", name: "Pickle", desc: "El humano primitivo de la era jurásica acostumbrado a cazar T-Rex.", room: "universo_lucha_mamados", tags: ["monstruo", "fuerza_bruta", "salvaje"], favoritePlace: "laboratorio_criogenico", universo: "Baki", hp: 500, fuerza: 94, defensa: 90, mana: 0, alineacion: "Neutral", habilidadEspecial: "Pletora Jurásica" },
    musashi_baki: { id: "musashi_baki", name: "Musashi Miyamoto", desc: "El legendario espadachín resucitado cortando el aire con sus manos desnudas.", room: "universo_lucha_mamados", tags: ["samurai", "dangerous", "sabio_serio"], favoritePlace: "dojo_tokio", universo: "Baki", hp: 370, fuerza: 80, defensa: 60, mana: 40, alineacion: "Neutral", habilidadEspecial: "Corte Invisible sin Espada" },
    motobe: { id: "motobe", name: "Izo Motobe", desc: "El maestro de jujutsu que juró 'proteger' a todos armándose hasta los dientes.", room: "universo_lucha_mamados", tags: ["estrategا", "ninja", "protector"], favoritePlace: "taller_armas", universo: "Baki", hp: 260, fuerza: 45, defensa: 45, mana: 50, alineacion: "Heroe", habilidadEspecial: "Jujutsu Táctico Armado" },

    // Kengan Ashura
    ohma_tokita: { id: "ohma_tokita", name: "Ohma Tokita (El Ashura)", desc: "El luchador del estilo Niko con la mirada ardiente buscando batallas.", room: "universo_lucha_mamados", tags: ["luchador", "heroico", "determinado"], favoritePlace: "barrio_interior", universo: "Kengan Ashura", hp: 360, fuerza: 78, defensa: 60, mana: 40, alineacion: "Heroe", habilidadEspecial: "Estilo Niko: Advance" },
    julius_reinhold: { id: "julius_reinhold", name: "Julius Reinhold", desc: "El monstruo alemán de la masa muscular puramente científica sin artes marciales.", room: "universo_lucha_mamados", tags: ["fuerza_bruta", "tanque", "serio"], favoritePlace: "laboratorio_esteroides", universo: "Kengan Ashura", hp: 480, fuerza: 92, defensa: 88, mana: 0, alineacion: "Neutral", habilidadEspecial: "Gott-Töter Steinbohrer" },
    raian_kure: { id: "raian_kure", name: "Raian Kure (El Diablo)", desc: "El asesino del clan Kure riendo desquiciadamente con ojos negros.", room: "universo_lucha_mamados", tags: ["caotico", "agresivo", "asesino"], favoritePlace: "villa_kure", universo: "Kengan Ashura", hp: 370, fuerza: 80, defensa: 62, mana: 30, alineacion: "Antiheroe", habilidadEspecial: "Removal 100%" },
    wakatsuki: { id: "wakatsuki", name: "Wakatsuki Takeshi (El Tigre Salvaje)", desc: "El veterano con densidad muscular 52 veces superior a un humano normal.", room: "universo_lucha_mamados", tags: ["fuerza_bruta", "noble", "luchador"], favoritePlace: "gimnasio_furumi", universo: "Kengan Ashura", hp: 440, fuerza: 88, defensa: 80, mana: 20, alineacion: "Heroe", habilidadEspecial: "Blast Core" },
    kanoh_agito: { id: "kanoh_agito", name: "Kanoh Agito (El Colmillo de Metsudo)", desc: "El emperador de las luchas Kengan cambiando entre estilo Formless y Marcial.", room: "universo_lucha_mamados", tags: ["luchador", "imponente", "estrategا"], favoritePlace: "arena_kengan", universo: "Kengan Ashura", hp: 410, fuerza: 84, defensa: 72, mana: 50, alineacion: "Heroe", habilidadEspecial: "Dragon Shot" },
    toa_mudo: { id: "toa_mudo", name: "Toa Mudo", desc: "El gigante maorí de la isla Purgatorio creyéndose un dios de la montaña.", room: "universo_lucha_mamados", tags: ["fuerza_bruta", "tanque", "orgulloso"], favoritePlace: "arena_purgatorio", universo: "Kengan Ashura", hp: 460, fuerza: 89, defensa: 84, mana: 10, alineacion: "Neutral", habilidadEspecial: "Redireccion Kahawai" },
    meguro_masaki: { id: "meguro_masaki", name: "Meguro Masaki", desc: "El judoka psicópata sangrando por los ojos de pura excitación por el dolor.", room: "universo_lucha_mamados", tags: ["caotico", "maniaco", "luchador"], favoritePlace: "sala_autopsias", universo: "Kengan Ashura", hp: 320, fuerza: 68, defensa: 50, mana: 0, alineacion: "Villano", habilidadEspecial: "Proyección Judo Asesina" },
    naidan: { id: "naidan", name: "Naidan Monkhbat", desc: "El luchador de bökh mongol con el tatuaje del Gusano en el brazo.", room: "universo_lucha_mamados", tags: ["serio", "luchador", "mysterioso"], favoritePlace: "estepa_mongola", universo: "Kengan Ashura", hp: 380, fuerza: 76, defensa: 68, mana: 30, alineacion: "Antiheroe", habilidadEspecial: "Ojo del Cielo" },
    haruo: { id: "haruo", name: "Haruo Sakurazaki (Haru)", desc: "El avatar de Indra de 300 kilos jugando consolas portátiles.", room: "universo_lucha_mamados", tags: ["fuerza_bruta", "gamer", "comelon"], favoritePlace: "tienda_videojuegos", universo: "Kengan Ashura", hp: 420, fuerza: 75, defensa: 60, mana: 10, alineacion: "Heroe", habilidadEspecial: "Embestida de Indra" },

    // General Shonen Jump & Muscle Anime
    yami_sukehiro: { id: "yami_sukehiro", name: "Yami Sukehiro", desc: "El capitán de los Toros Negros fumando con su katana envuelta en magia oscura.", room: "universo_shonen_jump", tags: ["lider", "fuerte", "comico", "heroico"], favoritePlace: "baño_sede", universo: "Black Clover", hp: 390, fuerza: 80, defensa: 65, mana: 110, alineacion: "Heroe", habilidadEspecial: "Corte de Dimension Oscura" },
    escanor: { id: "escanor", name: "Escanor (El León del Orgullo)", desc: "El Pecado del Orgullo portando a Rhitta en pleno mediodía irradiando calor.", room: "universo_shonen_jump", tags: ["orgulloso", "dios", "fuerza_bruta", "heroico"], favoritePlace: "taberna_boar_hat", universo: "Nanatsu no Taizai", hp: 480, fuerza: 95, defensa: 85, mana: 120, alineacion: "Heroe", habilidadEspecial: "Cruel Sun" },
    thors: { id: "thors", name: "Thors (El Troll de Jom)", desc: "El vikingo legendario capaz de noquear a guerreros armados a puño limpio.", room: "universo_anime_variado", tags: ["sabio_serio", "noble", "fuerza_bruta"], favoritePlace: "pueblo_islandia", universo: "Vinland Saga", hp: 400, fuerza: 85, defensa: 75, mana: 0, alineacion: "Heroe", habilidadEspecial: "Puño del Verdadero Guerrero" },
    thorkell: { id: "thorkell", name: "Thorkell el Alto", desc: "El gigante vikingo de 2.30m lanzando troncos con una risa eufórica de batalla.", room: "universo_anime_variado", tags: ["caotico", "fuerza_bruta", "comico"], favoritePlace: "campo_batalla_vikingo", universo: "Vinland Saga", hp: 450, fuerza: 90, defensa: 70, mana: 0, alineacion: "Neutral", habilidadEspecial: "Lanzamiento de Tronco Gigante" },
    armstrong: { id: "armstrong", name: "Alex Louis Armstrong", desc: "El Alquimista de Brazo Poderoso arrancándose la camisa para mostrar sus músculos.", room: "universo_shonen_jump", tags: ["heroico", "comico", "fuerza_bruta", "mago"], favoritePlace: "mansion_armstrong", universo: "Fullmetal Alchemist", hp: 330, fuerza: 70, defensa: 60, mana: 80, alineacion: "Heroe", habilidadEspecial: "Alquimia de Arte Escultural" },
    toguro_menor: { id: "toguro_menor", name: "Younger Toguro (100%)", desc: "El demonio con el 100% de su masa muscular distorsionando el aire a su paso.", room: "universo_shonen_jump", tags: ["villano", "fuerza_bruta", "imponente"], favoritePlace: "estadio_torneo_oscuro", universo: "Yu Yu Hakusho", hp: 460, fuerza: 91, defensa: 82, mana: 70, alineacion: "Villano", habilidadEspecial: "Bomba de Músculo Demoniaco" },
    kenichi: { id: "kenichi", name: "Ken-ichi Shirahama", desc: "El discípulo más fuerte de Ryōzanpaku combinando 6 estilos de artes marciales.", room: "universo_shonen_jump", tags: ["heroico", "determinado", "humilde"], favoritePlace: "dojo_ryozanpaku", universo: "Kenichi", hp: 280, fuerza: 54, defensa: 45, mana: 40, alineacion: "Heroe", habilidadEspecial: "Seikūken Ryōzanpaku Combo" }
};

// Instancias en memoria
export const npcInstances = {};

// Inicializar todas las instancias
export function initializeNPCs() {
    Object.keys(rawNpcsDB).forEach(key => {
        npcInstances[key] = new Personaje(rawNpcsDB[key]);
    });
}

// Funciones helper
export function getNpc(id) {
    const clave = id.toLowerCase().trim();
    return npcInstances[clave] || null;
}

export function getNpcsByRoom(roomKey) {
    return Object.values(npcInstances).filter(npc => npc.room === roomKey);
}

export function getNpcsByTag(tag) {
    return Object.values(npcInstances).filter(npc => npc.tags.includes(tag));
}

export function getNpcsByUniverso(universoNombre) {
    return Object.values(npcInstances).filter(npc => 
        npc.universo.toLowerCase() === universoNombre.toLowerCase()
    );
}

export function getAllNpcKeys() {
    return Object.keys(npcInstances);
}

export function searchNpcByName(busqueda) {
    const query = busqueda.toLowerCase().trim();
    return Object.values(npcInstances).filter(npc => 
        npc.name.toLowerCase().includes(query)
    );
}

export function findNPCInRoom(targetName, currentRoom) {
    const normalized = targetName.toLowerCase().trim();
    const npcsInRoom = getNpcsByRoom(currentRoom);
    
    for (const npc of npcsInRoom) {
        if (npc.id === normalized || 
            npc.name.toLowerCase().includes(normalized) ||
            npc.id.includes(normalized)) {
            return npc.id;
        }
    }
    return null;